import './style.css';
import QRCode from 'qrcode';
import { loadState, saveState, resetState, catalogGames, allPeople, canPlay, safeUrl, formatTime, isUnder } from './store.js';
import { t } from './i18n.js';
import { icon } from './icons.js';
import { firebaseAuth, firebaseReady } from './services/firebase.js';
import { firebaseData } from './services/firebaseData.js';
import { platformApi } from './services/platformApi.js';
import { encodeLaunchToken, decodeLaunchToken, buildLaunchUrl } from './protocol.js';
import { sendFriendRequest, acceptIncomingFriend, removeFriend, createReport, applyModeration, upsertSubmission, transitionSubmission, setSubmissionVisibility, scheduleSubmissionDeletion, cancelSubmissionDeletion, upsertUserReview, blockUser, preserveReportEvidence, expireSessionMessages } from './stateActions.js';
import { runSdkCheck } from './sdkCheck.js';

const root = document.querySelector('#app');
let state = loadState();
state.analytics ||= { launches: [], sdkErrors: [], joins: [] };
state.reportEvidence ||= [];
const messageCount=state.messages.length;
expireSessionMessages(state);
if(messageCount!==state.messages.length)saveState(state);
const getGames = () => catalogGames(state);
const presencePrivacy = () => ({visibility:state.settings.showStatus?(isUnder(state.user.dob,13)?'friends':'everyone'):'nobody',joinPrivacy:state.settings.invisible?'nobody':(isUnder(state.user.dob,13)&&state.settings.joinPrivacy==='everyone'?'friends':state.settings.joinPrivacy)});
const getPeople = () => {
  if(!firebaseReady||!state.cloudProfiles?.length)return allPeople();
  return state.cloudProfiles.filter(profile=>profile.id!==state.user.id&&!state.blocked.includes(profile.id)).map((profile,index)=>{
    const presence=state.cloudPresence?.[profile.id]||{state:'offline'},game=getGames().find(item=>item.id===presence.gameId);
    const joinAllowed=presence.joinPrivacy==='everyone'||(presence.joinPrivacy==='friends'&&state.friends.includes(profile.id));
    return {id:profile.id,name:profile.displayName||profile.username||'Player',username:profile.username||profile.id,status:presence.state||'offline',game:game?.title,gameId:presence.gameId,sessionId:presence.sessionId,joinable:Boolean(presence.joinable&&joinAllowed&&!state.settings.invisible),avatar:profile.avatar||['#FF8B62','#5FCCA6','#DD7DFF','#58A9E8','#D7C65D'][index%5],profilePublic:true,showFriends:profile.showFriends!==false,publishedGames:(state.cloudGames||[]).filter(item=>item.ownerId===profile.id&&item.status==='published').map(item=>item.title)};
  });
};
let route = 'home';
let selectedGame = null;
let modal = null;
let query = '';
let filters = { age: 'All', tag: 'All', players: 'All', device: 'Desktop' };
let activeThread = 'mila';
let toastTimer;
const launchChannels = new Map();
let cloudUnsubscribe = null;

const PL_UI = {
  'Close':'Zamknij','Friend actions':'Działania znajomego','Open conversation':'Otwórz rozmowę','Decline request':'Odrzuć zaproszenie','Quick play':'Szybka gra','Add emoji':'Dodaj emoji','Create group':'Utwórz grupę','Submission actions':'Działania zgłoszenia','Action':'Działanie','Categories':'Kategorie','Desktop':'Komputer','Multiplayer':'Wieloosobowa','Notify me':'Powiadom mnie','Explore as player':'Otwórz demo gracza','Explore admin demo':'Otwórz demo administratora','or sign in':'lub zaloguj się','Publish':'Opublikuj','Access denied':'Brak dostępu','Moderation requires a verified administrator role.':'Moderacja wymaga potwierdzonej roli administratora.','Return home':'Wróć na stronę główną','Chat unavailable':'Czat niedostępny','A parent or guardian must approve chat for this account.':'Rodzic lub opiekun musi zatwierdzić czat na tym koncie.','Allow chat':'Zezwól na czat','A parent can turn private, group and session chat off.':'Rodzic może wyłączyć czat prywatny, grupowy i sesyjny.','Choose whether this category appears in your notification center.':'Wybierz, czy ta kategoria ma trafiać do centrum powiadomień.',
  'Invisible':'Niewidoczny','THIS WEEK\'S DECK PICK':'WYBÓR TYGODNIA','Full':'Pełna','Play a game to see it here.':'Zagraj, aby zobaczyć grę w tym miejscu.',
  'THE FULL DECK':'PEŁNY KATALOG','Independent worlds, one reliable launch point.':'Niezależne światy w jednym pewnym miejscu.','All':'Wszystkie','Clear filters':'Wyczyść filtry',
  'SLOTS':'MIEJSC','Invite friend':'Zaproś znajomego','Requests':'Zaproszenia','Your friends':'Twoi znajomi','See who is around and move into the same game.':'Zobacz, kto jest dostępny, i dołącz do tej samej gry.',
  'Keep the crew together':'Trzymaj ekipę razem','Your party moves between games as one. Every game session has a hard limit of eight players.':'Twoja grupa przechodzi między grami razem. Każda sesja ma twardy limit ośmiu graczy.',
  'Launch party':'Grupa do gry','members':'osoby','No messages yet':'Nie ma jeszcze wiadomości','Say hello without sharing private contact details.':'Przywitaj się, nie udostępniając prywatnych danych kontaktowych.',
  'the party':'grupy','Text, emoji and safe links only. Images are not supported.':'Tylko tekst, emoji i bezpieczne linki. Zdjęcia nie są obsługiwane.',
  'CREATOR CONSOLE':'PANEL TWÓRCY','Ship through the deck':'Opublikuj grę w katalogu','Every game stays on its creator\'s hosting and must pass the GG SDK check.':'Każda gra pozostaje na hostingu twórcy i musi przejść test GG SDK.',
  'Total launches':'Łączne uruchomienia','Returning players':'Powracający gracze','Launch errors':'Błędy uruchamiania','Last 7 days':'Ostatnie 7 dni','Join usage':'Użycia „Dołącz”','Friend joins':'Dołączenia znajomych','this month':'w tym miesiącu','28 day retention':'retencja po 28 dniach',
  'Your submissions':'Twoje zgłoszenia','Game':'Gra','SDK':'SDK','Status':'Status','Updated':'Aktualizacja','Pass':'Zaliczony','Failed':'Niezaliczony',
  'GG SDK · OPEN SOURCE':'GG SDK · OPEN SOURCE','One handshake. Sessions that travel.':'Jedno połączenie. Sesje, które idą z Tobą.','Use the local package to verify launch tokens, publish presence and create joinable sessions without exposing passwords or private profile data.':'Użyj lokalnego pakietu do weryfikacji tokenów startowych, publikowania statusu i tworzenia sesji bez ujawniania haseł ani prywatnych danych profilu.','Read SDK docs':'Dokumentacja SDK',
  'ADMIN ONLY':'TYLKO ADMIN','Moderation desk':'Panel moderacji','Human decisions, visible context and a permanent audit trail.':'Decyzje podejmuje człowiek, z pełnym kontekstem i trwałą historią działań.','open':'otwarte',
  'Game approval queue':'Kolejka zatwierdzania gier','SDK PASS':'SDK ZALICZONY','SDK FAIL':'SDK NIEZALICZONY','Request changes':'Poproś o zmiany','Queue cleared.':'Kolejka jest pusta.','User & content reports':'Zgłoszenia użytkowników i treści','Warn':'Ostrzeż','Mute':'Wycisz','Suspend':'Zawieś','Ban':'Zablokuj na stałe','Dismiss':'Odrzuć zgłoszenie','No open reports.':'Brak otwartych zgłoszeń.','Audit log':'Historia działań',
  'Parent controls':'Kontrola rodzicielska','Account & data':'Konto i dane','Change avatar':'Zmień avatar','PNG, JPG or WebP · stored on this device in local mode':'PNG, JPG lub WebP · w trybie lokalnym plik zostaje na tym urządzeniu','Display name':'Nazwa wyświetlana','Permanent username':'Stały username','Only an administrator can change this.':'Może go zmienić wyłącznie administrator.','Bio':'Opis profilu',
  'English is the default. Polish copy is written for the interface, not machine-translated.':'Domyślnym językiem jest angielski. Polska wersja została napisana ręcznie dla tego interfejsu.','English':'Angielski',
  'Invisible mode':'Tryb niewidoczny','Hide your online status and current game. Joining is disabled while invisible.':'Ukryj status online i aktualną grę. W trybie niewidocznym inni nie mogą do Ciebie dołączać.','Show activity':'Pokazuj aktywność','Let eligible people see your status and current game.':'Pozwól uprawnionym osobom widzieć Twój status i aktualną grę.','Public friend list':'Publiczna lista znajomych','Show your friends on your public profile.':'Pokazuj znajomych na publicznym profilu.','Who can join me':'Kto może do mnie dołączyć','Everyone':'Wszyscy','Friends':'Znajomi','Nobody':'Nikt',
  'Local mode keeps account data only in this browser. Export is a readable JSON file. Deletion can be cancelled for 30 days in a connected backend.':'Tryb lokalny przechowuje dane konta wyłącznie w tej przeglądarce. Eksport tworzy czytelny plik JSON. W połączonym backendzie usunięcie można cofnąć przez 30 dni.','Reset demo':'Przywróć demo',
  'Back to games':'Wróć do gier','About this game':'O grze','Ratings & reviews':'Oceny i opinie','Up to':'Do','players':'graczy','Optional review':'Opcjonalna opinia','Post rating':'Opublikuj ocenę','Rating only':'Tylko ocena','this game':'tę grę',
  'ACTIVITY':'AKTYWNOŚĆ','Mark all as read':'Oznacz wszystkie jako przeczytane','CREATOR-HOSTED GAME':'GRA NA HOSTINGU TWÓRCY','GG SDK launch':'Start przez GG SDK','EXTERNAL LINK':'LINK ZEWNĘTRZNY','Leave the deck?':'Opuścić platformę?',
  'FRIEND INVITE':'ZAPROSZENIE DO ZNAJOMYCH','Bring someone in':'Zaproś kogoś','Share the exact username, invite link or code. Friend requests still require approval.':'Udostępnij dokładny username, link lub kod. Zaproszenie nadal wymaga akceptacji.','Invite link':'Link z zaproszeniem','Copy':'Kopiuj','Exact @username or display name':'Dokładny @username lub nazwa wyświetlana',
  'NEW SUBMISSION':'NOWE ZGŁOSZENIE','Send a game for review':'Wyślij grę do sprawdzenia','Only the technical minimum is required. You remain the sole owner.':'Wymagane jest tylko minimum techniczne. Pozostajesz jedynym właścicielem.','Title':'Tytuł','HTTPS game URL':'Adres HTTPS gry','Age rating':'Kategoria wiekowa','Free-form notes':'Dodatkowe informacje','Description, tags, controls, test notes…':'Opis, tagi, sterowanie, uwagi z testów…','My game passes the GG SDK handshake test':'Moja gra przechodzi test połączenia z GG SDK','Submit for review':'Wyślij do sprawdzenia','Remove friend':'Usuń znajomego','Not available':'Niedostępne',
  'ONE DECK. EVERY WORLD.':'JEDEN KATALOG. KAŻDY ŚWIAT.','Find independent games, see where your friends are and join the same session.':'Odkrywaj niezależne gry, sprawdzaj, gdzie są znajomi, i dołączaj do ich sesji.','LOCAL DEMO · FIREBASE READY':'LOKALNE DEMO · GOTOWE NA FIREBASE','Enter the deck':'Wejdź do katalogu','Email':'Email','Password':'Hasło','Continue with email':'Kontynuuj przez email','Continue with Google':'Kontynuuj przez Google','Continue with Apple':'Kontynuuj przez Apple','Requires Apple Developer configuration':'Wymaga konfiguracji Apple Developer','Local demo credentials are stored only in this browser. Firebase mode is enabled only when its public web configuration is supplied.':'Dane lokalnego konta są przechowywane tylko w tej przeglądarce. Tryb Firebase włącza się dopiero po dodaniu publicznej konfiguracji aplikacji webowej.',
  'YOUR IDENTITY':'TWOJA TOŻSAMOŚĆ','Pick a name\nthat stays.':'Wybierz nazwę,\nktóra zostaje.','Your first username becomes your permanent @username. You can change the display name later.':'Pierwszy username staje się stałym @username. Nazwę wyświetlaną możesz później zmienić.','ACCOUNT SETUP':'KONFIGURACJA KONTA','Create your profile':'Utwórz profil','Username':'Username','Date of birth':'Data urodzenia','Parent or guardian email':'Email rodzica lub opiekuna','Required for accounts under 13. A connected backend must verify consent before social features unlock.':'Wymagany dla osób poniżej 13 lat. Połączony backend musi potwierdzić zgodę, zanim odblokuje funkcje społecznościowe.','Create profile':'Utwórz profil','Your exact date of birth remains private. Games receive only an age band.':'Dokładna data urodzenia pozostaje prywatna. Gry otrzymują tylko przedział wiekowy.',
  'Arcade':'Zręcznościowa','Party':'Imprezowa','Puzzle':'Logiczna','Solo':'Solo','Strategy':'Strategiczna','Co-op':'Kooperacyjna','Survival':'Survival','Horror':'Horror',
  'A neon bowling night built for quick rounds, clean throws and loud couch rivalries.':'Neonowy bowling stworzony do szybkich rund, czystych rzutów i głośnej rywalizacji na kanapie.','Slide, merge and keep the board alive in a sharp future remix of a classic puzzle.':'Przesuwaj, łącz i utrzymaj planszę przy życiu w futurystycznej wersji klasycznej łamigłówki.','Move impossible cargo across Mars while the whole crew shares one beautiful disaster.':'Przewoź niemożliwe ładunki przez Marsa, gdy cała ekipa wspólnie przeżywa piękną katastrofę.','Turn flat images into physical paths and reshape the level through your camera.':'Zmieniaj płaskie obrazy w prawdziwe ścieżki i przebudowuj poziom za pomocą aparatu.','Survive a wide ocean, build a tiny home and keep your friends aboard.':'Przetrwaj na otwartym oceanie, zbuduj mały dom i utrzymaj znajomych na pokładzie.','Stay together. Mark the walls. The corridors remember where you have been.':'Trzymajcie się razem. Oznaczajcie ściany. Korytarze pamiętają, gdzie byliście.'
};
Object.assign(PL_UI,{
  'Every game stays on its creator\'s hosting and must pass a real GG SDK handshake.':'Każda gra pozostaje na hostingu twórcy i musi przejść prawdziwy test GG SDK.',
  'Submit a game':'Zgłoś grę','Total launches':'Łączne uruchomienia','Recorded locally':'Zapisane lokalnie','Returning launches':'Powtórne uruchomienia','Same player again':'Ponowne uruchomienie przez tę samą osobę','SDK connection':'Połączenie SDK','No submissions yet.':'Nie masz jeszcze zgłoszeń.','Edit submission':'Edytuj zgłoszenie','Hide':'Ukryj','Show':'Pokaż','Delete':'Usuń','Cancel deletion':'Anuluj usunięcie',
  'Permanent game ID':'Stały identyfikator gry','Run real SDK test':'Uruchom prawdziwy test SDK','Required before submission':'Wymagany przed wysłaniem','Passed for this URL':'Zaliczony dla tego adresu','Testing in a game window…':'Testowanie w oknie gry…','Waiting for signed ready handshake':'Oczekiwanie na poprawny handshake','Allow pop-ups and try again.':'Zezwól na wyskakujące okna i spróbuj ponownie.','No valid SDK ready handshake received.':'Nie otrzymano poprawnego handshake GG SDK.','Publish update':'Opublikuj aktualizację',
  'Independent worlds, one reliable launch point.':'Niezależne światy w jednym pewnym miejscu startowym.','Screenshots':'Materiały z gry','About this game':'O grze','Creator':'Twórca','Devices':'Urządzenia','Desktop · keyboard and mouse':'Komputer · klawiatura i mysz','Friends here':'Znajomi w tej grze','No friends playing now':'Żaden znajomy teraz nie gra','Popularity score':'Wynik popularności','Ratings & reviews':'Oceny i opinie','Optional review':'Opcjonalna opinia','Post rating':'Opublikuj ocenę','Rating only':'Tylko ocena',
  'Every launch runs through the open GG SDK so presence, parties and friend joins work consistently.':'Każde uruchomienie przechodzi przez otwarte GG SDK, dzięki czemu status, grupy i dołączanie znajomych działają spójnie.',
  'SDK pending':'SDK oczekuje','SDK integration pending':'Oczekuje na integrację SDK','This real game is listed now and will unlock after its GG SDK integration passes review.':'To prawdziwa gra z katalogu. Uruchamianie odblokuje się po dodaniu i zatwierdzeniu integracji GG SDK.','Action':'Akcja','Parkour':'Parkour','Multiplayer':'Wieloosobowa','New':'Nowa',
  'An open robot city where voice, AI characters and multiplayer collide.':'Otwarte miasto robotów, w którym spotykają się sterowanie głosem, postacie AI i multiplayer.','A physics-first pogo playground with three connected zones and multiplayer.':'Fizyczny plac zabaw na pogo z trzema połączonymi strefami i multiplayerem.','Fly as a missile through obstacle courses and finish with a voxel explosion.':'Leć jako pocisk przez tory przeszkód i zakończ trasę wielką wokselową eksplozją.','Fifteen compact pogo levels built for co-op runs on web and desktop.':'Piętnaście zwartych poziomów pogo przygotowanych do wspólnych przejść w przeglądarce i na komputerze.','Survive a wide ocean, build a tiny home and keep your friends aboard.':'Przetrwaj na otwartym oceanie, zbuduj mały dom i utrzymaj znajomych na pokładzie.','Turn flat images into physical paths and reshape the level through your camera.':'Zmieniaj płaskie obrazy w prawdziwe ścieżki i przebudowuj poziom za pomocą aparatu.','Stay together. Mark the walls. The corridors remember where you have been.':'Trzymajcie się razem. Oznaczajcie ściany. Korytarze pamiętają, gdzie byliście.',
  'Request changes':'Poproś o zmiany','Game approval queue':'Kolejka zatwierdzania gier','User & content reports':'Zgłoszenia użytkowników i treści','Warn':'Ostrzeż','Mute':'Wycisz','Suspend':'Zawieś','Ban':'Zablokuj na stałe','Dismiss':'Odrzuć','Queue cleared.':'Kolejka jest pusta.','No open reports.':'Brak otwartych zgłoszeń.','Human decisions, visible context and a permanent audit trail.':'Decyzje podejmuje człowiek, z widocznym kontekstem i trwałą historią działań.',
  'Currently playing':'Aktualnie gra','Joinable session':'Można dołączyć','Private or full session':'Sesja prywatna albo pełna','Published games':'Opublikowane gry','No published games':'Brak opublikowanych gier','No mutual friends':'Brak wspólnych znajomych','Friend list hidden':'Lista znajomych jest ukryta','Remove friend':'Usuń znajomego','Bring someone in':'Zaproś kogoś','Copy':'Kopiuj','Mark all as read':'Oznacz wszystkie jako przeczytane','Leave the deck?':'Opuścić platformę?',
  'Keep the crew together':'Trzymaj ekipę razem','See who is around and move into the same game.':'Zobacz, kto jest dostępny, i przejdźcie do tej samej gry.','No messages yet':'Nie ma jeszcze wiadomości','Say hello without sharing private contact details.':'Przywitaj się bez udostępniania prywatnych danych kontaktowych.','Text, emoji and safe links only. Images are not supported.':'Tylko tekst, emoji i bezpieczne linki. Zdjęcia nie są obsługiwane.','Create group':'Utwórz grupę',
  'Parent controls':'Kontrola rodzicielska','Approve as verified parent':'Zatwierdź jako zweryfikowany rodzic','Shared parent view':'Widok udostępniony rodzicowi','View child safety history':'Zobacz historię bezpieczeństwa dziecka','Who can join me':'Kto może do mnie dołączyć','Log out':'Wyloguj się','Reset demo':'Przywróć demo','Account & data':'Konto i dane','Change avatar':'Zmień avatar','Display name':'Nazwa wyświetlana','Permanent username':'Stały username','Bio':'Opis profilu',
  'Messages':'Wiadomości','Invites':'Zaproszenia','Verified parents can control chat, approve new friends and inspect the child safety history.':'Zweryfikowany rodzic może sterować czatem, zatwierdzać nowych znajomych i przeglądać historię bezpieczeństwa dziecka.','No connected child accounts.':'Brak połączonych kont dzieci.','Chat controlled by parent':'Czat kontrolowany przez rodzica','Enabled · this account cannot change it':'Włączony · to konto nie może tego zmienić','Disabled · this account cannot change it':'Wyłączony · to konto nie może tego zmienić','Approved child account':'Zatwierdzone konto dziecka','Consent request':'Prośba o zgodę','Disable chat':'Wyłącz czat','Enable chat':'Włącz czat','Friend approvals':'Zatwierdzanie znajomych','Approved':'Zatwierdzono',
  'approved':'zatwierdzona','rejected':'odrzucona','hidden':'ukryta','published':'opublikowana','submitted':'wysłana','requiredChanges':'wymaga zmian',
  'Arcade':'Zręcznościowa','Party':'Imprezowa','Puzzle':'Logiczna','Strategy':'Strategiczna','Co-op':'Kooperacyjna','Horror':'Horror','Survival':'Survival','Indie':'Niezależna'
});
const uiText = value => state.settings.language === 'pl' ? (PL_UI[value] || value) : value;

const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const tx = key => t(state, key);
const syncCloud = promise => promise?.catch?.(error=>console.warn('Firebase sync skipped:',error.message));
async function downscaleAvatar(file,size=96){const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const scale=Math.max(size/bitmap.width,size/bitmap.height);canvas.getContext('2d').drawImage(bitmap,(size-bitmap.width*scale)/2,(size-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);return canvas.toDataURL('image/webp',0.85);}
const persist = () => {saveState(state);if(firebaseReady&&state.auth.provider==='firebase'&&isUnder(state.user.dob,13))syncCloud(firebaseData.saveParentView(state.user.id,{friends:state.friends.slice(0,50),pendingFriendIds:[...new Set([...state.requests,...(state.friendApprovalQueue||[])])].slice(0,50),messageHistory:state.messages.slice(-500).map(message=>({thread:message.thread,from:message.from,text:message.text,at:message.at,kind:message.kind}))}));};
const publishCurrentPresence = () => {if(!firebaseReady||state.auth.provider!=='firebase')return;let current={status:'online',gameId:null,sessionId:null,joinable:false};try{current={...current,...JSON.parse(localStorage.getItem(`gg-presence-${state.user.id}`)||'{}')};}catch{}syncCloud(firebaseData.setPresence(state.user.id,{state:current.status||'online',gameId:current.gameId||null,sessionId:current.sessionId||null,joinable:Boolean(current.joinable),...presencePrivacy()}));};
const toast = text => { clearTimeout(toastTimer); document.querySelector('.toast')?.remove(); document.body.insertAdjacentHTML('beforeend', `<div class="toast" role="status">${icon('check')} ${esc(uiText(text))}</div>`); toastTimer = setTimeout(() => document.querySelector('.toast')?.remove(), 2600); };
function translateDynamic(text) {
  if (state.settings.language !== 'pl') return text;
  if (PL_UI[text]) return PL_UI[text];
  return text
    .replace(/SLOTS/g,'MIEJSC').replace(/^Requests ·/,'Zaproszenia ·').replace(/ members$/,' osoby').replace(/^Message /,'Napisz do ')
    .replace(/^Up to (\d+) players$/,'Do $1 graczy').replace(/ players$/,' graczy').replace(/ reviews$/,' opinii')
    .replace(/^deletes (.+)$/,'usunięcie $1')
    .replace(/^Report this game$/,'Zgłoś tę grę').replace(/^Back to games$/,'Wróć do gier').replace(/^No games match these filters\.$/,'Żadna gra nie pasuje do filtrów.')
    .replace(/^← Back to games$/,'← Wróć do gier').replace(/^Zgłoś this game$/,'Zgłoś tę grę')
    .replace(/^Online$/,'Online').replace(/^Offline$/,'Offline').replace(/^In game:/,'W grze:').replace(/^Playing$/,'W grze')
    .replace(/^Friend request sent to (.+)\.$/,'Zaproszenie do znajomych wysłano do $1.')
    .replace(/^(\d+) friends · (\d+) messages$/,'$1 znajomych · $2 wiadomości').replace(/^Approve (.+)$/,'Zatwierdź: $1')
    .replace(/^(\d+) stars$/,'$1 gwiazdek')
    .replace(/^Local seed game/,'Lokalna gra startowa');
}
function localizeDom() {
  if (state.settings.language === 'pl') {
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let node;
    while((node=walker.nextNode())) { const raw=node.nodeValue,trim=raw.trim(); if(trim){const translated=translateDynamic(trim);if(translated!==trim)node.nodeValue=raw.replace(trim,translated);} }
    root.querySelectorAll('[placeholder]').forEach(el=>el.placeholder=translateDynamic(el.placeholder));
    root.querySelectorAll('[title]').forEach(el=>el.title=translateDynamic(el.title));
    root.querySelectorAll('[aria-label]').forEach(el=>el.setAttribute('aria-label',translateDynamic(el.getAttribute('aria-label'))));
  }
  const fallback = el => {
    if(el.dataset.modalClose!==undefined)return uiText('Close');
    if(el.dataset.personMenu)return uiText('Friend actions'); if(el.dataset.thread)return uiText('Open conversation');
    if(el.dataset.decline)return uiText('Decline request'); if(el.dataset.favorite)return uiText('Favorite');
    if(el.dataset.action==='notifications')return tx('notifications'); if(el.dataset.action==='quick-play')return uiText('Quick play');
    if(el.dataset.action==='emoji')return uiText('Add emoji'); if(el.dataset.action==='new-group')return uiText('Create group');
    if(el.dataset.editSubmission)return uiText('Submission actions'); if(el.dataset.reportMessage)return tx('report');
    return uiText('Action');
  };
  root.querySelectorAll('button,a').forEach(el=>{if(!el.getAttribute('aria-label')&&!el.textContent.trim()){const label=fallback(el);el.setAttribute('aria-label',label);el.title=label;}});
}
const userAvatar = () => state.user.avatar ? `<img src="${state.user.avatar}" alt=""/>` : `<span>${esc(state.user.displayName.slice(0, 1))}</span>`;
const personAvatar = person => {const image=/^(data:|https?:)/.test(person.avatar||'')?`<img src="${esc(person.avatar)}" alt=""/>`:esc(person.name[0]);const color=/^#/.test(person.avatar||'')?person.avatar:'#7486FF';return `<span class="avatar" style="--avatar:${color}">${image}<i class="presence ${person.status}"></i></span>`;};
const ageAllowed = game => canPlay(state.user, game);
const playerWord=count=>state.settings.language==='pl'?(count===1?'gracz':'graczy'):tx('players');

function shell(content) {
  const nav = [['home','home'],['games','games'],['friends','friends'],['chat','chat'],['creator','creator'],...(state.user.role==='admin'?[['admin','admin']]:[])];
  return `<div class="shell">
    <aside class="rail">
      <button class="brand" data-route="home" aria-label="Gzowo's Games"><span>G</span><b>G</b></button>
      <nav>${nav.map(([id, label]) => `<button data-route="${id}" class="rail-link ${route === id ? 'active' : ''}" title="${tx(label)}">${icon(id)}<span>${tx(label)}</span></button>`).join('')}</nav>
      <button data-route="settings" class="rail-link ${route === 'settings' ? 'active' : ''}">${icon('settings')}<span>${tx('settings')}</span></button>
    </aside>
    <section class="workspace">
      <header class="topbar">
        <label class="global-search">${icon('search')}<input id="global-search" value="${esc(query)}" placeholder="${tx('search')}" autocomplete="off"/><kbd>⌘ K</kbd></label>
        <div class="top-actions"><span class="online-pill"><i></i>${state.settings.invisible ? 'Invisible' : 'Online'}</span><button class="icon-button" data-action="notifications" aria-label="${tx('notifications')}">${icon('bell')}${state.notifications.some(n=>!n.read)?'<b class="badge"></b>':''}</button><button class="profile-chip" data-route="settings"><span class="avatar self">${userAvatar()}</span><span><b>${esc(state.user.displayName)}</b><small>@${esc(state.user.username)}</small></span></button></div>
      </header>
      <main>${content}</main>
    </section>
    <div class="dock-notch"><button data-route="games">${icon('games')}<span>${tx('games')}</span></button><button data-action="quick-play" class="dock-play">${icon('play')}</button><button data-route="friends">${icon('friends')}<span>${tx('friends')}</span></button></div>
    ${modal ? renderModal() : ''}
  </div>`;
}

function sectionHead(title, action = '') { return `<div class="section-head"><h2>${title}</h2>${action}</div>`; }
function gameArt(game, large = false) { return `<div class="game-art ${large?'large':''}" style="--game:${game.color}"><span class="art-grid"></span><b>${esc(game.glyph)}</b><small>${esc(uiText(game.tags[0]))} / ${game.players}P</small></div>`; }
function gameCard(game) {
  const favorite = state.favorites.includes(game.id);
  return `<article class="game-card" data-game="${game.id}" tabindex="0">${gameArt(game)}<div class="card-copy"><div><h3>${esc(game.title)}</h3><p>${esc(game.tags.map(uiText).join(' · '))}</p></div><button class="heart ${favorite?'active':''}" data-favorite="${game.id}" aria-label="${favorite?tx('unfavorite'):tx('favorite')}">${icon('heart')}</button></div><div class="card-meta"><span>${icon('star')} ${game.reviews?game.rating:uiText('New')}</span><span><i class="live-dot"></i>${game.active} ${playerWord(game.active)}</span>${game.sdkReady?'':'<span class="sdk-pending">SDK pending</span>'}<span class="age">${game.age}</span></div></article>`;
}
function gameRow(game) { return `<button class="game-row" data-game="${game.id}">${gameArt(game)}<span><b>${esc(game.title)}</b><small>${esc(game.creator)} · ${game.tags.map(uiText).join(', ')}</small></span><span class="rating">${icon('star')} ${game.reviews?game.rating:uiText('New')}</span>${icon('arrow')}</button>`; }
const popularityScore = game => game.active*3 + game.rating*20 + game.reviews*.15 + (state.favorites.includes(game.id)?12:0) + (state.recently.includes(game.id)?8:0);

function homeView() {
  const games = getGames(); const featured = games.filter(g=>g.featured); const hero = featured[0] || games[0];
  const friendPlaying = getPeople().filter(p=>p.status==='playing');
  return `<div class="page home-page">
    <section class="hero">${gameArt(hero, true)}<div class="hero-copy"><span class="eyebrow">THIS WEEK'S DECK PICK</span><h1>${esc(hero.title)}</h1><p>${esc(uiText(hero.description))}</p><div class="hero-actions"><button class="primary" data-launch="${hero.id}">${icon('play')} ${tx('play')}</button><button class="secondary" data-game="${hero.id}">${tx('viewGame')}</button></div><div class="hero-stats"><span>${icon('star')} ${hero.reviews?hero.rating:uiText('New')} <small>(${hero.reviews})</small></span><span><i class="live-dot"></i>${hero.active} ${playerWord(hero.active)}</span><span>${hero.age}</span></div></div></section>
    <section>${sectionHead(tx('friendsPlaying'), `<button class="text-button" data-route="friends">${tx('friends')} ${icon('arrow')}</button>`)}<div class="friend-strip">${friendPlaying.map(p=>`<article class="friend-playing">${personAvatar(p)}<span><b>${esc(p.name)}</b><small>${esc(p.game)}</small></span><button class="mini ${p.joinable?'primary':'secondary'}" ${p.joinable?`data-join="${p.gameId}"`:`data-wait="${p.gameId}"`}>${p.joinable?tx('join'):'Notify me'}</button></article>`).join('')}</div></section>
    <section>${sectionHead(tx('featured'), `<button class="text-button" data-route="games">${tx('allGames')} ${icon('arrow')}</button>`)}<div class="game-grid">${featured.map(gameCard).join('')}</div></section>
    <section>${sectionHead(tx('newGames'))}<div class="game-grid">${[...games].sort((a,b)=>b.created.localeCompare(a.created)).slice(0,3).map(gameCard).join('')}</div></section>
    <section>${sectionHead('Categories')}<div class="chips">${[...new Set(games.flatMap(g=>g.tags))].map(tag=>`<button data-category="${esc(tag)}">${esc(tag)}</button>`).join('')}</div></section>
    <div class="split-sections"><section>${sectionHead(tx('popular'))}<div class="list-card">${[...games].sort((a,b)=>popularityScore(b)-popularityScore(a)).slice(0,4).map(gameRow).join('')}</div></section><section>${sectionHead(tx('recently'))}<div class="list-card">${state.recently.map(id=>games.find(g=>g.id===id)).filter(Boolean).map(gameRow).join('') || '<p class="empty">Play a game to see it here.</p>'}</div></section></div>
  </div>`;
}

function gamesView() {
  const games=getGames();
  const tags = ['All', ...new Set(games.flatMap(g=>g.tags))];
  const filtered = games.filter(g => (!query || `${g.title} ${g.creator} ${g.tags}`.toLowerCase().includes(query.toLowerCase())) && (filters.age==='All'||g.age===filters.age) && (filters.tag==='All'||g.tags.includes(filters.tag)) && (filters.players==='All'||(filters.players==='Solo'?g.players===1:g.players>1)));
  return `<div class="page"><div class="page-title"><div><span class="eyebrow">THE FULL DECK</span><h1>${tx('games')}</h1><p>Independent worlds, one reliable launch point.</p></div><span class="count">${filtered.length} / ${games.length}</span></div><div class="filterbar"><select data-filter="age"><option>All</option><option>E</option><option>13+</option><option>18+</option></select><select data-filter="players"><option>All</option><option>Solo</option><option>Multiplayer</option></select><select data-filter="device"><option>Desktop</option></select><div class="chips">${tags.map(tag=>`<button data-tag="${esc(tag)}" class="${filters.tag===tag?'active':''}">${esc(tag)}</button>`).join('')}</div></div><div class="game-grid catalog">${filtered.map(gameCard).join('')}</div>${filtered.length?'':`<div class="empty-state">${icon('search')}<h2>${tx('noResults')}</h2><button class="secondary" data-action="clear-filters">Clear filters</button></div>`}</div>`;
}

function friendsView() {
  const people=getPeople(); const friends=people.filter(p=>state.friends.includes(p.id)); const requests=people.filter(p=>state.requests.includes(p.id));
  return `<div class="page"><div class="page-title"><div><span class="eyebrow">${state.friends.length} / 50 SLOTS</span><h1>${tx('friends')}</h1><p>See who is around and move into the same game.</p></div><button class="primary" data-action="invite">${icon('plus')} Invite friend</button></div>
  ${requests.length?`<section>${sectionHead(`Requests · ${requests.length}`)}<div class="people-list">${requests.map(p=>personLine(p,'request')).join('')}</div></section>`:''}
  <section>${sectionHead('Your friends')}<div class="people-list">${friends.map(p=>personLine(p,'friend')).join('')}</div></section>
  <section class="party-panel"><div><span class="eyebrow">${tx('party').toUpperCase()} · ${state.party.length}/8</span><h2>Keep the crew together</h2><p>Your party moves between games as one. Every game session has a hard limit of eight players.</p><button class="text-button danger-text" data-report-group="party">${tx('report')} group</button></div><div class="party-avatars">${state.party.map(id=>{if(id===state.user.id)return `<span class="avatar self">${userAvatar()}</span>`;const person=people.find(p=>p.id===id);return person?personAvatar(person):'';}).join('')}<button data-action="party-add">${icon('plus')}</button></div></section></div>`;
}
function personLine(p, mode) { return `<article class="person-line">${personAvatar(p)}<span class="person-copy"><b>${esc(p.name)}</b><small>@${esc(p.username)} · ${p.status==='playing'?`${tx('inGame')}: ${p.game}`:tx(p.status)}</small></span>${p.status==='playing'?`<button class="secondary mini" ${p.joinable?`data-join="${p.gameId}"`:`data-wait="${p.gameId}"`}>${p.joinable?tx('join'):'Notify me'}</button>`:''}${mode==='request'?`<button class="primary mini" data-accept="${p.id}">${tx('approve')}</button><button class="icon-button" data-decline="${p.id}">${icon('close')}</button>`:`<button class="icon-button" data-thread="${p.id}">${icon('chat')}</button><button class="icon-button" data-person-menu="${p.id}">${icon('more')}</button>`}</article>`; }

function chatView() {
  if(isUnder(state.user.dob,13)&&(!state.user.parentConsent||state.parentControls?.chatEnabled!==true)) return `<div class="page empty-state"><h1>Chat unavailable</h1><p>A parent or guardian must approve chat for this account.</p><button class="secondary" data-route="home">Return home</button></div>`;
  const people=getPeople().filter(p=>state.friends.includes(p.id)); const msgs=state.messages.filter(m=>m.thread===activeThread && (m.kind!=='session'||Date.now()-m.at<86400000)); const active=people.find(p=>p.id===activeThread);
  return `<div class="page chat-layout"><aside class="thread-list"><div class="thread-head"><h1>${tx('chat')}</h1><button class="icon-button" data-action="new-group">${icon('plus')}</button></div><button class="thread ${activeThread==='party'?'active':''}" data-thread="party"><span class="avatar group">GG</span><span><b>Launch party</b><small>${state.party.length} members</small></span></button>${people.map(p=>`<button class="thread ${activeThread===p.id?'active':''}" data-thread="${p.id}">${personAvatar(p)}<span><b>${esc(p.name)}</b><small>${p.status==='offline'?tx('offline'):tx('online')}</small></span></button>`).join('')}</aside><section class="conversation"><header>${active?`${personAvatar(active)}<span><b>${esc(active.name)}</b><small>${active.status==='playing'?active.game:tx(active.status)}</small></span>`:`<span class="avatar group">GG</span><span><b>Launch party</b><small>${state.party.length}/8 members · group chat</small></span>`}<button class="icon-button">${icon('more')}</button></header><div class="messages">${msgs.length?msgs.map(m=>messageBubble(m)).join(''):'<div class="empty-state"><h2>No messages yet</h2><p>Say hello without sharing private contact details.</p></div>'}</div><form class="composer" id="chat-form"><button type="button" class="icon-button" data-action="emoji">☺</button><input name="message" maxlength="1000" placeholder="Message ${active?esc(active.name):'the party'}" autocomplete="off"/><button class="primary" type="submit">${tx('send')}</button><small>Text, emoji and safe links only. Images are not supported.</small></form></section></div>`;
}
function messageBubble(m) { const own=m.from===state.user.id; let text=esc(m.text).replace(/(https?:\/\/[^\s]+)/g, url=>`<button class="inline-link" data-link="${esc(url)}">${esc(url)}</button>`); return `<div class="message ${own?'own':''}"><small>${own?state.user.displayName:(getPeople().find(p=>p.id===m.from)?.name||m.from)} · ${formatTime(m.at)}</small><p>${text}</p><button data-report-message="${m.id}" class="message-more">${icon('more')}</button></div>`; }

function creatorView() {
  const own=state.submissions.filter(s=>s.owner===state.user.username);
  const ownIds=new Set(own.map(game=>game.id));
  const launches=state.analytics.launches.filter(event=>ownIds.has(event.gameId));
  const joins=state.analytics.joins.filter(event=>ownIds.has(event.gameId));
  const errors=state.analytics.sdkErrors.filter(event=>ownIds.has(event.gameId));
  const returning=Math.max(0,launches.length-new Set(launches.map(event=>event.userId)).size);
  const rows=own.map(s=>`<div class="table-row"><span><b>${esc(s.title)}</b><small>${esc(s.url)}${s.deleteAt?` · deletes ${new Date(s.deleteAt).toLocaleDateString()}`:''}</small></span><span class="sdk ${s.sdkPassed?'pass':'fail'}">${s.sdkPassed?'Pass':'Failed'}</span><span class="status ${s.status}">${esc(uiText(s.status))}${s.visibility==='hidden'?` · ${esc(uiText('hidden'))}`:''}</span><span>${s.updated||s.created}</span><span class="table-actions"><button class="icon-button" data-edit-submission="${s.id}" aria-label="Edit submission">${icon('more')}</button>${s.status==='published'&&!s.deleteAt?`<button class="text-button" data-toggle-game="${s.id}:${s.visibility==='hidden'?'show':'hide'}">${s.visibility==='hidden'?'Show':'Hide'}</button><button class="text-button danger-text" data-delete-game="${s.id}">Delete</button>`:''}${s.deleteAt?`<button class="text-button" data-cancel-delete="${s.id}">Cancel deletion</button>`:''}</span></div>`).join('');
  return `<div class="page"><div class="page-title"><div><span class="eyebrow">CREATOR CONSOLE</span><h1>Ship through the deck</h1><p>Every game stays on its creator's hosting and must pass a real GG SDK handshake.</p></div><button class="primary" data-action="new-submission">${icon('plus')} Submit a game</button></div><div class="metric-grid"><article><small>Total launches</small><b>${launches.length}</b><span>Recorded locally</span></article><article><small>Returning launches</small><b>${returning}</b><span>Same player again</span></article><article><small>Launch errors</small><b>${errors.length}</b><span>SDK connection</span></article><article><small>Join usage</small><b>${joins.length}</b><span>Friend joins</span></article></div><section>${sectionHead('Your submissions')}<div class="submission-table"><div class="table-head"><span>Game</span><span>SDK</span><span>Status</span><span>Updated</span><span></span></div>${rows||'<p class="empty">No submissions yet.</p>'}</div></section><section class="sdk-callout"><div class="code-mark">&lt;/&gt;</div><div><span class="eyebrow">GG SDK · OPEN SOURCE</span><h2>One handshake. Sessions that travel.</h2><p>Use the local package to verify launch tokens, publish presence and create joinable sessions without exposing passwords or private profile data.</p></div><a class="secondary" href="/sdk/README.md" target="_blank">Read SDK docs ${icon('arrow')}</a></section></div>`;
}

function adminView() {
  if(state.user.role!=='admin') return `<div class="page empty-state"><h1>Access denied</h1><p>Moderation requires a verified administrator role.</p><button class="secondary" data-route="home">Return home</button></div>`;
  const gameQueue=state.submissions.filter(s=>['submitted','approved'].includes(s.status)).map(s=>`<article><div><span class="eyebrow">${s.age} · ${s.sdk?'SDK PASS':'SDK FAIL'} · ${s.status}</span><h3>${esc(s.title)}</h3><p>${esc(s.notes)}</p><small>@${esc(s.owner)} · ${esc(s.url)}</small></div><div>${s.status==='submitted'?`<button class="secondary" data-review="${s.id}:requiredChanges">Request changes</button><button class="danger" data-review="${s.id}:rejected">${tx('reject')}</button><button class="primary" data-review="${s.id}:approved" ${!s.sdk?'disabled':''}>${tx('approve')}</button>`:`<button class="primary" data-review="${s.id}:published">Publish</button>`}</div></article>`).join('');
  const reports=state.moderation.filter(m=>m.status==='open').map(m=>`<article><div><span class="eyebrow">${m.created}</span><h3>${esc(m.target)}</h3><p>${esc(m.reason)}</p><small>${esc(m.context)}</small></div><div class="moderation-actions"><button data-moderate="${m.id}:warning">Warn</button><button data-moderate="${m.id}:mute">Mute</button><button data-moderate="${m.id}:suspend">Suspend</button><button class="danger" data-moderate="${m.id}:ban">Ban</button><button class="secondary" data-moderate="${m.id}:dismiss">Dismiss</button></div></article>`).join('');
  return `<div class="page"><div class="page-title"><div><span class="eyebrow">ADMIN ONLY</span><h1>Moderation desk</h1><p>Human decisions, visible context and a permanent audit trail.</p></div><span class="count">${state.moderation.filter(m=>m.status==='open').length} open</span></div><div class="admin-grid"><section><h2>Game approval queue</h2><div class="queue">${gameQueue||'<p class="empty">Queue cleared.</p>'}</div></section><section><h2>User & content reports</h2><div class="queue">${reports||'<p class="empty">No open reports.</p>'}</div></section></div><section>${sectionHead('Audit log')}<div class="audit">${state.audit.slice().reverse().map(a=>`<p><span>${new Date(a.at).toLocaleString()}</span><b>${esc(a.action)}</b><small>by @${esc(a.by)}</small></p>`).join('')}</div></section></div>`;
}

function settingsView() {
  return `<div class="page settings-layout"><aside><h1>${tx('settings')}</h1><button class="active" data-settings-target="profile">${tx('profile')}</button><button data-settings-target="privacy">${tx('privacy')}</button><button data-settings-target="notification-settings">${tx('notifications')}</button><button data-settings-target="parent-controls">Parent controls</button><button data-settings-target="account-data">Account & data</button></aside><div class="settings-panels"><form class="settings-card" id="profile"><h2>${tx('profile')}</h2><div class="profile-editor"><label class="avatar-upload"><span class="avatar self large-avatar">${userAvatar()}</span><input type="file" name="avatar" accept="image/png,image/jpeg,image/webp"/><b>Change avatar</b><small>PNG, JPG or WebP · stored on this device in local mode</small></label><div class="form-grid"><label>Display name<input name="displayName" value="${esc(state.user.displayName)}" required maxlength="40"/></label><label>Permanent username<input value="@${esc(state.user.username)}" disabled/><small>Only an administrator can change this.</small></label><label class="full">Bio<textarea name="bio" maxlength="240">${esc(state.user.bio)}</textarea></label></div></div><button class="primary" type="submit">${tx('save')}</button></form>
  <section class="settings-card"><h2>${tx('language')}</h2><p>English is the default. Polish copy is written for the interface, not machine-translated.</p><div class="segmented"><button data-language="en" class="${state.settings.language==='en'?'active':''}">English</button><button data-language="pl" class="${state.settings.language==='pl'?'active':''}">Polski</button></div></section>
  <section class="settings-card" id="privacy"><h2>${tx('privacy')}</h2>${toggle('invisible','Invisible mode','Hide your online status and current game. Joining is disabled while invisible.')}${toggle('showStatus','Show activity','Let eligible people see your status and current game.')}${toggle('showFriends','Public friend list','Show your friends on your public profile.')}<label>Who can join me<select data-setting="joinPrivacy"><option value="everyone" ${state.settings.joinPrivacy==='everyone'?'selected':''}>Everyone</option><option value="friends" ${state.settings.joinPrivacy==='friends'?'selected':''}>Friends</option><option value="nobody" ${state.settings.joinPrivacy==='nobody'?'selected':''}>Nobody</option></select></label></section>
  <section class="settings-card" id="notification-settings"><h2>${tx('notifications')}</h2>${Object.entries(state.settings.notifications).map(([key,value])=>`<label class="toggle-row"><span><b>${key[0].toUpperCase()+key.slice(1)}</b><small>Choose whether this category appears in your notification center.</small></span><input type="checkbox" data-notification="${key}" ${value?'checked':''}/><i></i></label>`).join('')}</section>
  ${parentControlsPanel()}
  <section class="settings-card" id="account-data"><h2>Account & data</h2><p>${state.user.deletionRequestedAt?`Deletion scheduled for ${new Date(state.user.deletionRequestedAt+30*86400000).toLocaleDateString()}. Sign in before that date to cancel.`:'Local mode keeps account data only in this browser. Export is a readable JSON file. Deletion can be cancelled for 30 days in a connected backend.'}</p><div class="button-row"><button class="secondary" data-action="export">${icon('download')} ${tx('exportData')}</button><button class="danger" data-action="delete-account">${state.user.deletionRequestedAt?'Cancel deletion':tx('deleteAccount')}</button>${state.auth.provider==='firebase'&&!state.user.emailVerified?`<button class="secondary" data-action="verify-email">Verify email</button>`:''}<button class="secondary" data-action="logout">Log out</button><button class="ghost" data-action="reset">Reset demo</button></div></section></div></div>`;
}
function parentControlsPanel(){
  if(isUnder(state.user.dob,13)){const controls=state.parentControls||{chatEnabled:false,approvedFriendIds:[]};return `<section class="settings-card" id="parent-controls"><h2>Parent controls</h2><p>Consent: ${state.user.parentConsent?'approved':'awaiting approval'} · ${esc(state.user.parentEmail)}</p><div class="person-line"><span><b>Chat controlled by parent</b><small>${controls.chatEnabled?'Enabled':'Disabled'} · this account cannot change it</small></span></div><details><summary>Shared parent view</summary><p>${state.friends.length} friends · ${state.messages.length} retained messages</p></details></section>`;}
  const requests=state.parentApprovalRequests||[];
  const cards=requests.map(request=>{const view=state.parentChildViews?.[request.childUid],controls=state.parentChildControls?.[request.childUid]||{chatEnabled:false,approvedFriendIds:[]},pending=view?.pendingFriendIds||[];return `<article class="parent-child-card"><div class="person-line"><span><b>${request.status==='approved'?'Approved child account':'Consent request'}</b><small>${esc(request.childUid)}${view?` · ${view.friends?.length||0} friends · ${view.messageHistory?.length||0} messages`:''}</small></span>${request.status==='pending'?`<button class="primary mini" data-parent-approve="${esc(request.childUid)}">Approve as verified parent</button>`:`<button class="secondary mini" data-parent-chat="${esc(request.childUid)}:${controls.chatEnabled?'off':'on'}">${controls.chatEnabled?'Disable chat':'Enable chat'}</button>`}</div>${pending.length?`<div class="parent-friend-requests"><b>Friend approvals</b>${pending.map(friendId=>`<button class="secondary mini" data-parent-friend="${esc(request.childUid)}:${esc(friendId)}" ${controls.approvedFriendIds?.includes(friendId)?'disabled':''}>${controls.approvedFriendIds?.includes(friendId)?'Approved':`Approve ${esc(getPeople().find(person=>person.id===friendId)?.name||friendId)}`}</button>`).join('')}</div>`:''}${view?`<details><summary>View child safety history</summary>${(view.messageHistory||[]).map(message=>`<p><b>${esc(message.from)}</b>: ${esc(message.text)}</p>`).join('')}</details>`:''}</article>`;}).join('');
  return `<section class="settings-card" id="parent-controls"><h2>Parent controls</h2><p>Verified parents can control chat, approve new friends and inspect the child safety history.</p>${cards||'<p>No connected child accounts.</p>'}</section>`;
}
function toggle(key,title,desc){return `<label class="toggle-row"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox" data-setting="${key}" ${state.settings[key]?'checked':''}/><i></i></label>`;}

function detailView(game) {
  game={...game,description:uiText(game.description)};
  const favorite=state.favorites.includes(game.id),reviews=state.reviews.filter(r=>r.gameId===game.id),allowed=ageAllowed(game),friends=getPeople().filter(person=>person.gameId===game.id&&state.friends.includes(person.id));
  const reviewAuthor=review=>review.user||getPeople().find(person=>person.id===review.userId)?.name||'Player';
  const screenshots=[0,1,2].map(index=>`<div class="game-card">${gameArt({...game,glyph:`${game.glyph}${index+1}`})}</div>`).join('');
  const playable=allowed&&game.sdkReady;
  const integrationCopy=game.sdkReady?'Every launch runs through the open GG SDK so presence, parties and friend joins work consistently.':'This real game is listed now and will unlock after its GG SDK integration passes review.';
  return `<div class="page detail-page"><button class="back" data-action="back">← Back to games</button><section class="detail-hero">${gameArt(game,true)}<div><span class="eyebrow">${esc(game.tags.map(uiText).join(' · '))} · ${game.age}</span><h1>${esc(game.title)}</h1><p>${esc(game.description)}</p><div class="hero-actions"><button class="primary" data-launch="${game.id}" ${!playable?'disabled':''}>${icon('play')} ${!allowed?`Age ${game.age}`:game.sdkReady?tx('play'):uiText('SDK integration pending')}</button><button class="secondary ${favorite?'selected':''}" data-favorite="${game.id}">${icon('heart')} ${favorite?tx('unfavorite'):tx('favorite')}</button></div><div class="hero-stats"><span>${icon('star')} ${game.rating} <small>(${game.reviews})</small></span><span><i class="live-dot"></i>${game.active} ${tx('players')}</span><span>Up to ${game.players} players</span></div></div></section><section>${sectionHead('Screenshots')}<div class="game-grid">${screenshots}</div></section><div class="detail-columns"><section><h2>About this game</h2><p>${esc(game.description)} ${esc(uiText(integrationCopy))}</p><dl><dt>Creator</dt><dd>${esc(game.creator)}</dd><dt>Devices</dt><dd>Desktop · keyboard and mouse</dd><dt>Friends here</dt><dd>${friends.length?friends.map(friend=>esc(friend.name)).join(', '):'No friends playing now'}</dd><dt>Popularity score</dt><dd>${Math.round(popularityScore(game))}</dd></dl><div class="tag-list">${game.tags.map(x=>`<span>${esc(uiText(x))}</span>`).join('')}</div><button class="text-button danger-text" data-report-game="${game.id}" data-report-context="detail:${game.id}">${tx('report')} this game</button></section><section class="review-panel"><h2>Ratings & reviews</h2><div class="rating-big"><b>${game.rating}</b><span>${'★'.repeat(Math.round(game.rating))}${'☆'.repeat(5-Math.round(game.rating))}<small>${game.reviews} ${tx('reviews')}</small></span></div><form id="review-form" data-game-id="${game.id}"><div class="star-picker">${[1,2,3,4,5].map(n=>`<button type="button" data-star="${n}" aria-label="${n} stars">☆</button>`).join('')}</div><textarea name="review" maxlength="500" placeholder="Optional review"></textarea><input type="hidden" name="stars" value="0"/><button class="secondary" type="submit">Post rating</button></form>${reviews.map(r=>`<article class="review"><b>${esc(reviewAuthor(r))} <span>${'★'.repeat(r.stars)}</span></b><p>${esc(r.text)||'<em>Rating only</em>'}</p><small>${r.date}</small></article>`).join('')}</section></div></div>`;
}

function renderModal(){
  if(modal.type==='notifications') return modalShell(`<span class="eyebrow">ACTIVITY</span><h2>${tx('notifications')}</h2><div class="notification-list">${state.notifications.map(n=>`<article class="${n.read?'':'unread'}"><i></i><div><b>${esc(n.text)}</b><small>${formatTime(n.at)}</small></div></article>`).join('')}</div><button class="secondary full" data-action="read-all">Mark all as read</button>`,'side');
  if(modal.type==='launch'){const game=getGames().find(g=>g.id===modal.gameId),friend=modal.join?getPeople().find(p=>p.gameId===game.id&&p.joinable):null;return modalShell(`<span class="eyebrow">CREATOR-HOSTED GAME</span><h2>${esc(game.title)}</h2><p>${friend?`Join ${esc(friend.name)} in session ${esc(friend.sessionId)}.`:tx('launchWarning')}</p><div class="launch-token"><small>GG SDK launch · ${friend?'join':'new session'}</small><code>${platformApi.configured?'ES256 token issued after confirmation':esc(createLaunchToken(game,friend))}</code></div><div class="button-row"><button class="secondary" data-modal-close>${tx('cancel')}</button><button class="primary" data-confirm-launch="${game.id}">${tx('continue')} ${icon('arrow')}</button></div>`);}
  if(modal.type==='link') return modalShell(`<span class="eyebrow">EXTERNAL LINK</span><h2>Leave the deck?</h2><p>${tx('linkWarning')}</p><code class="url-preview">${esc(modal.url)}</code><div class="button-row"><button class="secondary" data-modal-close>${tx('cancel')}</button><a class="primary" href="${esc(modal.url)}" target="_blank" rel="noopener noreferrer" data-modal-close>${tx('continue')}</a></div>`);
  if(modal.type==='invite') return modalShell(`<span class="eyebrow">FRIEND INVITE</span><h2>Bring someone in</h2><p>Share the exact username, invite link or code. Friend requests still require approval.</p><div id="qr-code" class="qr"></div><label>Invite link<div class="copy-field"><input readonly value="https://games.gzowo.dev/invite/${state.user.username}-GG42"/><button data-action="copy-invite">Copy</button></div></label><form id="friend-search"><label>Exact @username or display name<input name="friend" placeholder="@username" required/></label><button class="primary full">${tx('request')}</button></form>`);
  if(modal.type==='submission') return modalShell(`<span class="eyebrow">NEW SUBMISSION</span><h2>Send a game for review</h2><p>Only the technical minimum is required. You remain the sole owner.</p><div class="launch-token"><small>Permanent game ID</small><code>${esc(modal.submissionId)}</code></div><form id="submission-form" class="stack-form"><label>Title<input name="title" required maxlength="80"/></label><label>HTTPS game URL<input name="url" required type="url" placeholder="https://"/></label><label>Age rating<select name="age"><option>E</option><option>13+</option><option>18+</option></select></label><label>Free-form notes<textarea name="notes" placeholder="Description, tags, controls, test notes…"></textarea></label><div class="sdk-test-row"><button class="secondary" type="button" data-action="test-sdk">Run real SDK test</button><span data-sdk-result>${modal.sdkCheck?.passed?'Passed for this URL':'Required before submission'}</span></div><button class="primary full">${modal.existingStatus==='published'?'Publish update':'Submit for review'}</button></form>`);
  if(modal.type==='person') {const p=getPeople().find(x=>x.id===modal.personId);if(p.profilePublic===false)return modalShell(`<span class="eyebrow">PRIVATE PROFILE</span>${personAvatar(p)}<h2>${esc(p.name)}</h2><p>@${esc(p.username)} keeps this profile private.</p>`);const mutuals=(p.mutualFriends||[]).filter(id=>state.friends.includes(id)).map(id=>getPeople().find(person=>person.id===id)?.name).filter(Boolean);return modalShell(`<span class="eyebrow">PUBLIC PROFILE</span>${personAvatar(p)}<h2>${esc(p.name)}</h2><p>@${esc(p.username)} · ${tx(p.status==='playing'?'inGame':p.status)}</p>${p.game?`<div class="launch-token"><small>Currently playing</small><b>${esc(p.game)}</b><span>${p.joinable?'Joinable session':'Private or full session'}</span></div>`:''}<p>${p.showFriends!==false?(mutuals.length?`Mutual friends: ${mutuals.map(esc).join(', ')}`:'No mutual friends'):'Friend list hidden'}</p><p><b>Published games</b><br>${(p.publishedGames||[]).length?p.publishedGames.map(esc).join(', '):'No published games'}</p><div class="stack-buttons">${p.joinable?`<button class="primary" data-join="${p.gameId}">${tx('join')}</button>`:''}<button class="secondary" data-thread="${p.id}">${tx('chat')}</button><button class="secondary" data-block="${p.id}">${tx('block')}</button><button class="danger" data-report-person="${p.id}">${tx('report')}</button><button class="ghost" data-remove-friend="${p.id}">Remove friend</button></div>`);}
  return modalShell('<h2>Not available</h2>');
}
function modalShell(content, mode='center'){return `<div class="modal-layer ${mode}" data-modal-close><section class="modal" role="dialog" aria-modal="true" onclick="event.stopPropagation()"><button class="modal-close" data-modal-close>${icon('close')}</button>${content}</section></div>`;}
function launchRequest(game,friend=null){return {gameId:game.id,party:state.party.slice(0,8),sessionId:friend?.sessionId||crypto.randomUUID(),joinData:friend?.joinData||{mode:'create'},permissions:['profile:basic','presence:write','session:create','session:join']};}
function createLaunchToken(game,friend=null){const request=launchRequest(game,friend),gameOrigin=new URL(game.url,location.href).origin;return encodeLaunchToken({v:1,sub:state.user.id,name:state.user.displayName,avatar:state.user.avatar||null,game:game.id,gameOrigin,platformOrigin:location.origin,age:isUnder(state.user.dob,13)?'U13':isUnder(state.user.dob,18)?'13-17':'18+',party:request.party,sessionId:request.sessionId,joinData:request.joinData,permissions:request.permissions,nonce:crypto.randomUUID(),exp:Date.now()+300000});}
async function issueLaunchToken(game,friend=null){if(platformApi.configured)return (await platformApi.launch(launchRequest(game,friend))).token;return createLaunchToken(game,friend);}
function startLaunchBridge(token,game,child){const payload=decodeLaunchToken(token);let ready=false;const handle=message=>{if(message?.source!=='gzowos-games-sdk'||message.nonce!==payload.nonce)return;if(message.type==='ready'){ready=true;toast(`${game.title} connected through GG SDK.`);}if(message.type==='presence'){localStorage.setItem(`gg-presence-${state.user.id}`,JSON.stringify({...message.payload,updatedAt:Date.now()}));void firebaseData.setPresence(state.user.id,{state:message.payload.status,gameId:game.id,sessionId:message.payload.sessionId,joinable:message.payload.joinable,...presencePrivacy()});}if(message.type==='session')void firebaseData.createSession(state.user.id,message.payload);};const onWindowMessage=event=>{if(event.source!==child||event.origin!==payload.gameOrigin)return;handle(event.data);};window.addEventListener('message',onWindowMessage);if(payload.gameOrigin===location.origin&&typeof BroadcastChannel!=='undefined'){const channel=new BroadcastChannel(`gg-launch-${payload.nonce}`);channel.onmessage=event=>handle(event.data);launchChannels.set(payload.nonce,channel);}setTimeout(()=>{if(!ready){state.analytics.sdkErrors.push({gameId:game.id,userId:state.user.id,at:Date.now(),reason:'ready-timeout'});persist();}},15000);setTimeout(()=>{window.removeEventListener('message',onWindowMessage);launchChannels.get(payload.nonce)?.close();launchChannels.delete(payload.nonce);},300000);}

function applyCloudData(data){
  if(data.profiles)state.cloudProfiles=data.profiles;
  if(data.presence)state.cloudPresence=data.presence;
  if(data.games)state.cloudGames=data.games.map(game=>{const owner=state.cloudProfiles?.find(profile=>profile.id===game.ownerId);return {...game,owner:owner?.username||owner?.displayName||'Independent creator',age:game.ageRating||game.age,created:game.publishedAt?.toDate?.().toISOString().slice(0,10)||game.publishedAt||game.updatedAt?.toDate?.().toISOString().slice(0,10)||new Date().toISOString().slice(0,10),deleteAt:game.deleteAt?.toMillis?.()||game.deleteAt||null};});
  if(data.reviews)state.reviews=data.reviews;
  if(data.notifications)state.notifications=data.notifications;
  if(data.preferences){const preferences=data.preferences;state.settings={...state.settings,...(preferences.settings||{})};if(preferences.favorites)state.favorites=preferences.favorites;if(preferences.blocked)state.blocked=preferences.blocked;}
  if(data.friendships){state.friends=data.friendships.filter(item=>item.status==='accepted').map(item=>item.members.find(member=>member!==state.user.id)).filter(Boolean);state.requests=data.friendships.filter(item=>item.status==='pending'&&item.senderId!==state.user.id).map(item=>item.senderId);state.outgoingRequests=data.friendships.filter(item=>item.status==='pending'&&item.senderId===state.user.id).map(item=>item.members.find(member=>member!==state.user.id)).filter(Boolean);}
  if(data.threads){state.cloudThreads=data.threads;data.threads.forEach(thread=>{const key=thread.members.length>2?'party':thread.members.find(member=>member!==state.user.id);if(key)state.threadIds[key]=thread.id;});}
  if(data.messages){const threads=state.cloudThreads||[];state.messages=data.messages.map(message=>{const thread=threads.find(item=>item.id===message.threadId),key=thread?.members?.length>2?'party':thread?.members?.find(member=>member!==state.user.id);return {id:message.id,thread:key||message.threadId,from:message.authorId||message.from,text:message.text,at:message.at,kind:message.kind};});expireSessionMessages(state);}
  if(data.reports)state.moderation=data.reports;
  persist();render();
}
function startCloudSync(user){cloudUnsubscribe?.();cloudUnsubscribe=null;state.party=[user.id,...state.party.filter(id=>id!==user.id&&id!=='local-jurek')].slice(0,8);syncCloud(firebaseData.setPresence(user.id,{state:'online',gameId:null,sessionId:null,joinable:false,...presencePrivacy()}));syncCloud(firebaseData.subscribeAccount(user.id,{admin:user.role==='admin',onData:applyCloudData}).then(unsubscribe=>{cloudUnsubscribe=unsubscribe;}));}

function render(){
  if(!state.auth.signedIn) { root.innerHTML=authView(); localizeDom(); bind(); return; }
  if(!state.user.onboarded) { root.innerHTML=setupView(); localizeDom(); bind(); return; }
  let content=selectedGame?detailView(getGames().find(game=>game.id===selectedGame.id)||selectedGame):({home:homeView,games:gamesView,friends:friendsView,chat:chatView,creator:creatorView,admin:adminView,settings:settingsView}[route]||homeView)();
  root.innerHTML=shell(content); localizeDom(); bind(); if(modal?.type==='invite') setTimeout(()=>QRCode.toCanvas(document.createElement('canvas'),`https://games.gzowo.dev/invite/${state.user.username}-GG42`,{width:160,margin:0,color:{dark:'#090B10',light:'#F3F5F8'}}).then(canvas=>document.querySelector('#qr-code')?.append(canvas)),0);
}
function authView(){return `<main class="auth-screen"><section class="auth-brand"><div class="brand huge"><span>G</span><b>G</b></div><span class="eyebrow">ONE DECK. EVERY WORLD.</span><h1>Gzowo’s<br/>Games</h1><p>Find independent games, see where your friends are and join the same session.</p></section><section class="auth-card"><span class="eyebrow">LOCAL DEMO · FIREBASE READY</span><h2>Enter the deck</h2><div class="demo-choices"><button class="primary" data-demo="user">Explore as player</button><button class="secondary" data-demo="admin">Explore admin demo</button></div><div class="divider"><span>or sign in</span></div><form id="auth-form"><label>Email<input type="email" name="email" value="jurek@example.com" required/></label><label>Password<input type="password" name="password" value="demo-pass-123" minlength="8" required/></label><button class="provider full">Continue with email</button></form><button class="provider" data-provider="google">G&nbsp; Continue with Google</button><button class="provider" data-provider="apple">●&nbsp; Continue with Apple <small>Requires Apple Developer configuration</small></button><p class="legal">Demo roles are explicit and local. In Firebase mode, administrator access requires a trusted custom claim; it is never granted by the browser.</p></section></main>`;}
function setupView(){return `<main class="auth-screen"><section class="auth-brand"><div class="brand huge"><span>G</span><b>G</b></div><span class="eyebrow">YOUR IDENTITY</span><h1>Pick a name<br/>that stays.</h1><p>Your first username becomes your permanent @username. You can change the display name later.</p></section><section class="auth-card"><span class="eyebrow">ACCOUNT SETUP</span><h2>Create your profile</h2><form id="setup-form"><label>Username<input name="username" pattern="[A-Za-z0-9_]{3,20}" maxlength="20" required placeholder="3–20 letters, numbers or _"/></label><label>Date of birth<input type="date" name="dob" required/></label><label id="parent-field" hidden>Parent or guardian email<input type="email" name="parentEmail"/><small>Required for accounts under 13. A connected backend must verify consent before social features unlock.</small></label><button class="primary full">Create profile</button></form><p class="legal">Your exact date of birth remains private. Games receive only an age band.</p></section></main>`;}

function bind(){
  document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>{route=el.dataset.route; selectedGame=null; modal=null; render();});
  document.querySelectorAll('[data-game]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-favorite]'))return;selectedGame=getGames().find(g=>g.id===el.dataset.game);render();});
  document.querySelectorAll('[data-favorite]').forEach(el=>el.onclick=e=>{e.stopPropagation();const id=el.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];persist();syncCloud(firebaseData.savePreferences(state.user.id,{favorites:state.favorites}));render();});
  document.querySelectorAll('[data-launch]').forEach(el=>el.onclick=()=>{if(!el.disabled){modal={type:'launch',gameId:el.dataset.launch};render();}});
  document.querySelectorAll('[data-join]').forEach(el=>el.onclick=()=>{if(!el.disabled){modal={type:'launch',gameId:el.dataset.join,join:true};render();}});
  document.querySelectorAll('[data-modal-close]').forEach(el=>el.onclick=()=>{modal=null;render();});
  document.querySelector('[data-action="notifications"]')?.addEventListener('click',()=>{modal={type:'notifications'};render();});
  document.querySelector('[data-action="read-all"]')?.addEventListener('click',()=>{state.notifications.forEach(n=>n.read=true);persist();render();});
  document.querySelector('[data-action="invite"]')?.addEventListener('click',()=>{modal={type:'invite'};render();});
  document.querySelector('[data-action="new-submission"]')?.addEventListener('click',()=>{modal={type:'submission',submissionId:crypto.randomUUID(),isNew:true,sdkCheck:null};render();});
  document.querySelector('[data-action="back"]')?.addEventListener('click',()=>{selectedGame=null;render();});
  document.querySelector('[data-action="clear-filters"]')?.addEventListener('click',()=>{query='';filters={age:'All',tag:'All',players:'All',device:'Desktop'};render();});
  document.querySelector('[data-action="quick-play"]')?.addEventListener('click',()=>{modal={type:'launch',gameId:state.recently[0]||'bowling'};render();});
  document.querySelectorAll('[data-thread]').forEach(el=>el.onclick=()=>{activeThread=el.dataset.thread;route='chat';selectedGame=null;render();});
  document.querySelectorAll('[data-person-menu]').forEach(el=>el.onclick=()=>{modal={type:'person',personId:el.dataset.personMenu};render();});
  document.querySelectorAll('[data-accept]').forEach(el=>el.onclick=()=>{const id=el.dataset.accept;if(!acceptIncomingFriend(state,id))return toast(state.outgoingRequests.includes(id)?'A sender cannot approve their own request.':'Friend request cannot be accepted.');persist();syncCloud(firebaseData.respondFriend([state.user.id,id].sort().join('_'),'accepted'));syncCloud(firebaseData.syncFriendAccess(state.user.id,id,true));toast('Friend request accepted.');render();});
  document.querySelectorAll('[data-accept]').forEach(el=>{const previous=el.onclick;el.onclick=()=>{if(isUnder(state.user.dob,13)&&(!state.user.parentConsent||!state.parentControls?.approvedFriendIds?.includes(el.dataset.accept)))return toast('A parent must approve this friend request first.');previous();};});
  document.querySelectorAll('[data-decline]').forEach(el=>el.onclick=()=>{const id=el.dataset.decline;state.requests=state.requests.filter(x=>x!==id);persist();syncCloud(firebaseData.respondFriend([state.user.id,id].sort().join('_'),'declined'));render();});
  document.querySelectorAll('[data-filter]').forEach(el=>{el.value=filters[el.dataset.filter];el.onchange=()=>{filters[el.dataset.filter]=el.value;render();};});
  document.querySelectorAll('[data-tag]').forEach(el=>el.onclick=()=>{filters.tag=el.dataset.tag;render();});
  document.querySelectorAll('[data-category]').forEach(el=>el.onclick=()=>{filters.tag=el.dataset.category;route='games';render();});
  document.querySelectorAll('[data-language]').forEach(el=>el.onclick=()=>{state.settings.language=el.dataset.language;persist();syncCloud(firebaseData.savePreferences(state.user.id,{settings:state.settings}));render();});
  document.querySelectorAll('[data-settings-target]').forEach(el=>el.onclick=()=>{document.querySelector(`#${el.dataset.settingsTarget}`)?.scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('[data-settings-target]').forEach(x=>x.classList.toggle('active',x===el));});
  document.querySelectorAll('[data-notification]').forEach(el=>el.onchange=()=>{state.settings.notifications[el.dataset.notification]=el.checked;persist();syncCloud(firebaseData.savePreferences(state.user.id,{settings:state.settings}));});
  document.querySelectorAll('[data-parent-approve]').forEach(el=>el.onclick=async()=>{if(firebaseReady&&!platformApi.configured)return toast('Trusted parent-consent backend is required.');if(firebaseReady){try{await platformApi.approveParentConsent(el.dataset.parentApprove);}catch(error){return toast(error.message);}}state.parentApprovalRequests=(state.parentApprovalRequests||[]).filter(request=>request.childUid!==el.dataset.parentApprove);persist();toast('Parental consent approved.');render();});
  document.querySelectorAll('[data-parent-chat]').forEach(el=>el.onclick=()=>{const [childUid,value]=el.dataset.parentChat.split(':'),current=state.parentChildControls?.[childUid]||{approvedFriendIds:[]},controls={...current,chatEnabled:value==='on'};state.parentChildControls={...(state.parentChildControls||{}),[childUid]:controls};persist();syncCloud(firebaseData.setParentControls(childUid,controls));render();});
  document.querySelectorAll('[data-parent-friend]').forEach(el=>el.onclick=()=>{const [childUid,friendId]=el.dataset.parentFriend.split(':'),current=state.parentChildControls?.[childUid]||{chatEnabled:false,approvedFriendIds:[]},controls={...current,approvedFriendIds:[...new Set([...(current.approvedFriendIds||[]),friendId])]};state.parentChildControls={...(state.parentChildControls||{}),[childUid]:controls};persist();syncCloud(firebaseData.setParentControls(childUid,controls));render();});
  document.querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{let val=el.type==='checkbox'?el.checked:el.value;if(el.dataset.setting==='joinPrivacy'&&isUnder(state.user.dob,13)&&val==='everyone'){el.value='friends';return toast('Under-13 accounts cannot allow everyone to join.');}state.settings[el.dataset.setting]=val;if(el.dataset.setting==='invisible'&&val)state.settings.joinPrivacy='nobody';persist();syncCloud(firebaseData.savePreferences(state.user.id,{settings:state.settings}));syncCloud(firebaseData.savePublicPrivacy(state.user.id,{showFriends:state.settings.showFriends,showStatus:state.settings.showStatus}));publishCurrentPresence();render();});
  document.querySelector('#global-search')?.addEventListener('input',e=>{query=e.target.value;if(route!=='games'||selectedGame){route='games';selectedGame=null;}render();document.querySelector('#global-search')?.focus();});
  document.querySelector('#chat-form')?.addEventListener('submit',async e=>{e.preventDefault();const input=e.currentTarget.message,text=input.value.trim();if(!text)return;const kind=activeThread==='party'?'group':'private';if(firebaseReady&&!platformApi.configured)return toast('Trusted chat backend is required.');let cloudThread=state.threadIds[activeThread];if(firebaseReady&&!cloudThread){const members=activeThread==='party'?state.party:[state.user.id,activeThread],ref=await platformApi.createThread(members,activeThread==='party'?'Launch party':'Private chat');cloudThread=ref?.id;if(cloudThread)state.threadIds[activeThread]=cloudThread;}if(cloudThread){await platformApi.sendMessage(cloudThread,text,kind);}else{state.messages.push({id:crypto.randomUUID(),thread:activeThread,from:state.user.id,text,at:Date.now(),kind});}persist();render();document.querySelector('#chat-form input')?.focus();});
  document.querySelector('[data-action="emoji"]')?.addEventListener('click',()=>{const input=document.querySelector('#chat-form input');if(input){input.value+=' 🎮';input.focus();}});
  document.querySelector('[data-action="new-group"]')?.addEventListener('click',async()=>{if(firebaseReady&&!platformApi.configured)return toast('Trusted chat backend is required.');activeThread='party';const ref=firebaseReady?await platformApi.createThread(state.party,'Launch party'):null;if(ref?.id)state.threadIds.party=ref.id;persist();toast('Group conversation opened.');render();});
  document.querySelector('[data-action="party-add"]')?.addEventListener('click',()=>{if(state.party.length>=8)return toast('The party is full.');const next=state.friends.find(id=>!state.party.includes(id));if(!next)return toast('Every available friend is already in the party.');state.party.push(next);persist();toast('Friend added to the party.');render();});
  document.querySelectorAll('[data-wait]').forEach(el=>el.onclick=()=>{const person=getPeople().find(p=>p.gameId===el.dataset.wait&&!p.joinable),sessionId=person?.sessionId||`wait-${el.dataset.wait}`;state.notifications.unshift({id:crypto.randomUUID(),text:`We will notify you when a ${getGames().find(g=>g.id===el.dataset.wait)?.title||'game'} slot opens.`,type:'invite',read:false,at:Date.now()});persist();syncCloud(firebaseData.joinWaitlist(state.user.id,sessionId));toast('Waitlist notification enabled.');render();});
  document.querySelectorAll('[data-link]').forEach(el=>el.onclick=()=>{const checked=safeUrl(el.dataset.link);if(!checked.ok)return toast('This link is blocked for safety.');modal={type:'link',url:checked.url.href};render();});
  document.querySelectorAll('[data-star]').forEach(el=>el.onclick=()=>{const input=document.querySelector('#review-form [name="stars"]');input.value=el.dataset.star;document.querySelectorAll('[data-star]').forEach(x=>x.textContent=Number(x.dataset.star)<=Number(el.dataset.star)?'★':'☆');});
  document.querySelector('#review-form')?.addEventListener('submit',e=>{e.preventDefault();const stars=Number(e.currentTarget.stars.value);if(!stars)return toast('Choose 1–5 stars first.');const game=getGames().find(g=>g.id===e.currentTarget.dataset.gameId),text=e.currentTarget.review.value.trim(),result=upsertUserReview(state,{gameId:game.id,userId:state.user.id,user:state.user.displayName,stars,text,date:new Date().toISOString().slice(0,10)});if(result.previousStars){game.rating=Number(((game.rating*game.reviews-result.previousStars+stars)/game.reviews).toFixed(1));}else{game.rating=Number(((game.rating*game.reviews+stars)/(game.reviews+1)).toFixed(1));game.reviews+=1;}state.gameStats[game.id]={rating:game.rating,reviews:game.reviews};persist();syncCloud(firebaseData.saveReview(game.id,state.user.id,{stars,text}));toast(result.previousStars?'Rating updated.':'Rating posted.');render();});
  document.querySelector('#profile')?.addEventListener('submit',e=>{e.preventDefault();state.user.displayName=e.currentTarget.displayName.value.trim();state.user.bio=e.currentTarget.bio.value.trim();persist();syncCloud(firebaseData.saveProfile(state.user));toast('Profile saved.');render();});
  document.querySelector('#profile [name="avatar"]')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file||file.size>1_500_000)return toast('Choose an image under 1.5 MB.');if(firebaseReady){try{state.user.avatar=await firebaseData.uploadAvatar(state.user.id,file);await firebaseData.saveProfile(state.user);persist();render();return;}catch{/* Storage needs Blaze on new Spark projects — fall back to an inline thumbnail. */}try{state.user.avatar=await downscaleAvatar(file);await firebaseData.saveProfile(state.user);persist();render();return;}catch(error){return toast(`Avatar upload failed: ${error.message}`);}}const reader=new FileReader();reader.onload=()=>{state.user.avatar=reader.result;persist();render();};reader.readAsDataURL(file);});
  if(modal?.submissionId){const current=state.submissions.find(s=>s.id===modal.submissionId),form=document.querySelector('#submission-form');if(current&&form){form.title.value=current.title;form.url.value=current.url;form.age.value=current.age;form.notes.value=current.notes||'';modal.existingStatus=current.status;}}
  document.querySelector('[data-action="test-sdk"]')?.addEventListener('click',async e=>{const form=document.querySelector('#submission-form'),checked=safeUrl(form?.url.value);if(!checked.ok)return toast('Use a valid HTTPS game URL first.');if(!platformApi.configured)return toast('A trusted backend is required for SDK verification.');const button=e.currentTarget,resultNode=document.querySelector('[data-sdk-result]');button.disabled=true;button.textContent='Testing in a game window…';resultNode.textContent='Waiting for signed ready handshake';const result=await runSdkCheck({url:checked.url.href,gameId:modal.submissionId,createChallenge:(gameId,url)=>platformApi.createSdkCheck(gameId,url),getChallenge:id=>platformApi.getSdkCheck(id)});button.disabled=false;button.textContent='Run real SDK test';if(result.passed){modal.sdkCheck={...result,url:checked.url.href};resultNode.textContent='Passed for this URL';toast('GG SDK handshake passed.');}else{modal.sdkCheck=null;resultNode.textContent=result.reason==='popup-blocked'?'Allow pop-ups and try again.':'No valid server-confirmed SDK handshake received.';toast('SDK check failed.');}});
  document.querySelector('#submission-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),checked=safeUrl(f.get('url'));if(!checked.ok)return toast('Use a valid HTTPS game URL.');const existing=state.submissions.find(s=>s.id===modal?.submissionId),sdkPassed=modal?.sdkCheck?.passed&&modal.sdkCheck.url===checked.url.href;if(!sdkPassed||!platformApi.configured)return toast('Run and pass the server-confirmed SDK test for this exact URL.');const id=modal.submissionId,status=existing?.status==='published'?'published':'submitted',today=new Date().toISOString().slice(0,10);try{await platformApi.claimSdkCheck(modal.sdkCheck.challengeId,{gameId:id,title:f.get('title'),url:checked.url.href,ageRating:f.get('age'),notes:f.get('notes')});}catch(error){return toast(error.message);}const update={title:f.get('title'),url:checked.url.href,age:f.get('age'),ageRating:f.get('age'),notes:f.get('notes'),status,owner:state.user.username,ownerId:state.user.id,sdk:true,sdkPassed:true,sdkCheckedAt:modal.sdkCheck.checkedAt,created:existing?.created||today,updated:today,visibility:existing?.visibility||'visible'};upsertSubmission(state,id,update);persist();const cloudGame={title:update.title,ageRating:update.ageRating,status,ownerId:state.user.id,notes:update.notes,visibility:update.visibility,...(existing?.status==='published'?{pendingUrl:checked.url.href}:{url:checked.url.href})};syncCloud(firebaseData.saveGame(id,cloudGame));modal=null;toast(status==='published'?'Update sent for automatic safety check.':existing?'Submission resubmitted.':'Game submitted for review.');render();});
  document.querySelectorAll('[data-edit-submission]').forEach(el=>el.onclick=()=>{const current=state.submissions.find(s=>s.id===el.dataset.editSubmission);modal={type:'submission',submissionId:current.id,existingStatus:current.status,sdkCheck:null};render();});
  document.querySelector('#friend-search')?.addEventListener('submit',e=>{e.preventDefault();const value=e.currentTarget.friend.value.trim().replace(/^@/,'').toLowerCase(),person=getPeople().find(p=>p.username.toLowerCase()===value||p.name.toLowerCase()===value);if(!person)return toast('No matching user found.');if(isUnder(state.user.dob,13)&&!state.parentControls?.approvedFriendIds?.includes(person.id)){state.friendApprovalQueue=[...new Set([...(state.friendApprovalQueue||[]),person.id])];persist();modal=null;toast('A parent must approve this friend first.');render();return;}if(!sendFriendRequest(state,person.id))return toast('This person is already connected or pending.');state.friendApprovalQueue=(state.friendApprovalQueue||[]).filter(id=>id!==person.id);persist();syncCloud(firebaseData.requestFriend(state.user.id,person.id));toast(`Friend request sent to ${person.name}.`);modal=null;render();});
  document.querySelector('[data-action="copy-invite"]')?.addEventListener('click',()=>{navigator.clipboard?.writeText(`https://games.gzowo.dev/invite/${state.user.username}-GG42`);toast('Invite link copied.');});
  document.querySelectorAll('[data-review]').forEach(el=>el.onclick=()=>{const [id,status]=el.dataset.review.split(':'),sub=transitionSubmission(state,id,status);if(!sub)return toast('That lifecycle transition is not allowed.');state.audit.push({id:crypto.randomUUID(),action:`${status} ${sub.title}`,by:state.user.username,at:Date.now()});state.notifications.unshift({id:crypto.randomUUID(),text:`${sub.title}: ${status}.`,type:'creator',read:false,at:Date.now()});persist();syncCloud(firebaseData.saveGame(id,{status,publishedAt:sub.publishedAt||null}));render();});
  document.querySelectorAll('[data-toggle-game]').forEach(el=>el.onclick=()=>{const [id,action]=el.dataset.toggleGame.split(':'),sub=setSubmissionVisibility(state,id,action==='show');if(!sub)return;persist();syncCloud(firebaseData.saveGame(id,{visibility:sub.visibility}));toast(action==='show'?'Game restored to the catalog.':'Game hidden immediately.');render();});
  document.querySelectorAll('[data-delete-game]').forEach(el=>el.onclick=()=>{const sub=scheduleSubmissionDeletion(state,el.dataset.deleteGame);if(!sub)return;persist();syncCloud(firebaseData.saveGame(sub.id,{visibility:'hidden',deleteAt:sub.deleteAt}));toast('Game hidden and scheduled for deletion in 30 days.');render();});
  document.querySelectorAll('[data-cancel-delete]').forEach(el=>el.onclick=()=>{const sub=cancelSubmissionDeletion(state,el.dataset.cancelDelete);if(!sub)return;persist();syncCloud(firebaseData.saveGame(sub.id,{visibility:'visible',deleteAt:null}));toast('Deletion cancelled and game restored.');render();});
  document.querySelectorAll('[data-moderate]').forEach(el=>el.onclick=async()=>{const [id,action]=el.dataset.moderate.split(':');if(firebaseReady&&!platformApi.configured)return toast('Trusted moderation backend is required.');if(firebaseReady){try{await platformApi.moderateReport(id,action);}catch(error){return toast(error.message);}}const item=applyModeration(state,id,action);if(!item)return;state.audit.push({id:crypto.randomUUID(),action:`${action}: ${item.target}`,by:state.user.username,at:Date.now()});persist();render();});
  document.querySelectorAll('[data-report-person],[data-report-game],[data-report-message],[data-report-group]').forEach(el=>el.onclick=()=>{const target=el.dataset.reportPerson||el.dataset.reportGame||el.dataset.reportMessage||el.dataset.reportGroup,context=el.dataset.reportContext||`${route}:${activeThread}:${target}`,id=crypto.randomUUID(),targetKind=el.dataset.reportPerson?'account':el.dataset.reportGame?'game':el.dataset.reportMessage?'message':'group',report=createReport(state,{id,target,targetKind,context,date:new Date().toISOString().slice(0,10)});if(targetKind==='message')preserveReportEvidence(state,target);syncCloud(platformApi.configured?platformApi.createReport({targetId:String(target),targetKind,reason:report.reason}):firebaseData.createReport(report.id,{target,targetKind,reporterId:state.user.id,reason:report.reason,context,status:'open'}));persist();modal=null;toast('Report sent with relevant context.');render();});
  document.querySelectorAll('[data-block]').forEach(el=>el.onclick=()=>{const id=el.dataset.block;blockUser(state,id);persist();syncCloud(firebaseData.savePreferences(state.user.id,{blocked:state.blocked}));syncCloud(firebaseData.syncFriendAccess(state.user.id,id,false));modal=null;toast('User blocked.');render();});
  document.querySelectorAll('[data-remove-friend]').forEach(el=>el.onclick=()=>{const id=el.dataset.removeFriend,friendshipId=[state.user.id,id].sort().join('_');removeFriend(state,id);persist();syncCloud(firebaseData.syncFriendAccess(state.user.id,id,false));syncCloud(firebaseData.deleteFriend(friendshipId));modal=null;render();});
  document.querySelector('[data-confirm-launch]')?.addEventListener('click',async e=>{const game=getGames().find(g=>g.id===e.currentTarget.dataset.confirmLaunch),friend=modal?.join?getPeople().find(p=>p.gameId===game.id&&p.joinable):null,event={gameId:game.id,userId:state.user.id,at:Date.now()},child=window.open('about:blank','_blank');if(!child){state.analytics.sdkErrors.push({...event,reason:'popup-blocked'});persist();return toast('Pop-up blocked. Allow pop-ups to launch games.');}try{const token=await issueLaunchToken(game,friend);state.analytics.launches.push(event);if(friend)state.analytics.joins.push(event);state.recently=[game.id,...state.recently.filter(x=>x!==game.id)].slice(0,8);persist();startLaunchBridge(token,game,child);child.location.href=buildLaunchUrl(game.url,token,location.href);modal=null;render();}catch(error){try{child.close();}catch{}state.analytics.sdkErrors.push({...event,reason:'token-issue-failed'});persist();toast(error.message);}});
  document.querySelector('[data-action="export"]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gzowos-games-data.json';a.click();URL.revokeObjectURL(a.href);});
  document.querySelector('[data-action="delete-account"]')?.addEventListener('click',()=>{if(state.user.deletionRequestedAt){delete state.user.deletionRequestedAt;persist();syncCloud(firebaseData.scheduleAccountDeletion(state.user.id,null));toast('Account deletion cancelled.');render();return;}if(confirm(uiText('Schedule account deletion with a 30-day cancellation period?'))){state.user.deletionRequestedAt=Date.now();persist();syncCloud(firebaseData.scheduleAccountDeletion(state.user.id,state.user.deletionRequestedAt));toast('Account deletion scheduled for 30 days from now.');render();}});
  document.querySelector('[data-action="reset"]')?.addEventListener('click',resetState);
  document.querySelector('[data-action="verify-email"]')?.addEventListener('click',async()=>{try{await firebaseAuth.sendVerification();toast('Verification email sent. Check your inbox, then sign in again.');}catch(error){toast(error.message);}});
  document.querySelector('[data-action="logout"]')?.addEventListener('click',async()=>{if(firebaseReady&&state.auth.provider==='firebase'){await firebaseData.setPresence(state.user.id,{state:'offline',gameId:null,sessionId:null,joinable:false,...presencePrivacy()});cloudUnsubscribe?.();cloudUnsubscribe=null;await firebaseAuth.logout();}state.auth={signedIn:false,provider:null,demoRole:null};persist();render();});
  document.querySelector('#auth-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(firebaseReady){try{await firebaseAuth.email(f.get('email'),f.get('password'));}catch(err){return toast(err.message);}}state.auth={signedIn:true,provider:firebaseReady?'firebase-email':'local-demo'};state.user.email=f.get('email');if(!firebaseReady)state.user.onboarded=false;persist();render();});
  document.querySelectorAll('[data-demo]').forEach(el=>el.onclick=()=>{const role=el.dataset.demo;state.auth={signedIn:true,provider:'local-demo',demoRole:role};state.user.role=role;state.user.onboarded=true;persist();render();});
  document.querySelector('#setup-form [name="dob"]')?.addEventListener('change',e=>{const under=isUnder(e.target.value,13),field=document.querySelector('#parent-field');field.hidden=!under;field.querySelector('input').required=under;});
  document.querySelector('#setup-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),username=String(f.get('username')).toLowerCase(),dob=String(f.get('dob')),parentEmail=String(f.get('parentEmail')||'');if(/admin|moderator|gzowo.?games|fuck|shit|kurw|chuj/i.test(username))return toast('That username is reserved or not allowed.');if(getPeople().some(p=>p.username.toLowerCase()===username))return toast('That username is already taken.');if(firebaseReady&&!platformApi.configured)return toast('Trusted identity backend is required.');if(firebaseReady){try{await platformApi.onboard(dob,parentEmail);}catch(error){return toast(error.message);}}state.user.username=username;state.user.displayName=f.get('username');state.user.dob=dob;state.user.parentEmail=parentEmail;state.user.parentConsent=!isUnder(dob,13);state.user.onboarded=true;persist();syncCloud(firebaseData.claimUsername(state.user.id,username));syncCloud(firebaseData.saveProfile(state.user));render();});
  document.querySelectorAll('[data-provider]').forEach(el=>el.onclick=async()=>{if(el.dataset.provider==='apple')return toast('Apple sign-in needs an Apple Developer configuration.');if(!firebaseReady)return toast('Add Firebase web config to enable Google sign-in.');try{await firebaseAuth.google();state.auth={signedIn:true,provider:'google'};state.user.onboarded=false;persist();render();}catch(err){toast(err.message);}});
}

document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#global-search')?.focus();}if(e.key==='Escape'&&modal){modal=null;render();}});
render();
if(firebaseReady) firebaseAuth.observe(async user=>{
  if(state.auth.provider==='local-demo')return;
  if(!user){cloudUnsubscribe?.();cloudUnsubscribe=null;state.auth={signedIn:false,provider:null,demoRole:null};persist();render();return;}
  state.auth={signedIn:true,provider:'firebase'};
  state.user={...state.user,id:user.id,email:user.email,emailVerified:user.emailVerified,displayName:user.displayName||state.user.displayName,role:user.role};
  // Returning accounts: rebuild local state from the cloud profile so login on
  // a fresh browser does not re-run onboarding (the trusted API would 409).
  try{const own=await firebaseData.loadOwnProfile(user.id);
    if(own?.profile?.username){state.user.username=own.profile.username;state.user.displayName=own.profile.displayName||own.profile.username;state.user.bio=own.profile.bio||state.user.bio;state.user.avatar=own.profile.avatar||state.user.avatar;state.user.onboarded=true;}
    else if(state.auth.provider==='firebase')state.user.onboarded=false;
    if(own?.identity){state.user.dob=own.identity.dateOfBirth;state.user.parentEmail=own.identity.parentEmail||'';if(own.identity.ageBand!=='U13')state.user.parentConsent=true;}
    if(own?.preferences){if(own.preferences.favorites)state.favorites=own.preferences.favorites;if(own.preferences.settings)state.settings={...state.settings,...own.preferences.settings};if(own.preferences.blocked)state.blocked=own.preferences.blocked;}
  }catch{}
  startCloudSync(user);
  persist();
  syncCloud(firebaseData.watchParentConsent(user.id,approved=>{if(approved){state.user.parentConsent=true;persist();render();}}));
  if(user.emailVerified)syncCloud(firebaseData.watchParentRequests(user.email,requests=>{
    state.parentApprovalRequests=requests;
    requests.filter(request=>request.status==='approved').forEach(request=>{
      syncCloud(firebaseData.watchParentView(request.childUid,view=>{state.parentChildViews={...(state.parentChildViews||{}),[request.childUid]:view};persist();render();}));
      syncCloud(firebaseData.watchParentControls(request.childUid,controls=>{state.parentChildControls={...(state.parentChildControls||{}),[request.childUid]:controls};persist();render();}));
    });
    persist();render();
  }));
  if(isUnder(state.user.dob,13))syncCloud(firebaseData.watchParentControls(user.id,controls=>{state.parentControls=controls;persist();render();}));
  render();
});
