import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { EventEmitter } from 'node:events';
import { Readable } from 'node:stream';
import { pathToFileURL } from 'node:url';
import { createApp,deriveAgeBand } from '../server/app.js';
import { createJwks,generateES256KeyPair,signES256,verifyES256 } from '../server/crypto/jws.js';
import { MemoryRepository } from '../server/repository/memory.js';
import { createNodePinnedTransport } from '../server/security/nodePinnedFetch.js';
import { isPrivateAddress } from '../server/security/url.js';

const now=1_800_000_000_000,issuer='https://games.example',gameOrigin='https://game.example';
async function setup(){const key=await generateES256KeyPair({kid:'security'}),repository=new MemoryRepository({games:[{id:'bowling',ownerId:'player',url:`${gameOrigin}/`,origin:gameOrigin,status:'published',visibility:'visible',sdkPassed:true,ageRating:'E',permissions:['profile:basic']}],ageBands:{player:'18+'},threads:[{id:'allowed',members:['player','friend']}],messages:[{id:'secret',threadId:'allowed',authorId:'friend',text:'proof',kind:'session',createdAt:now-1,expiresAt:now-1}],friendships:[['player','friend']],chatAllowed:{player:true,friend:true,blocked:false}}),claims=[];const authenticate=async request=>{const value=request.headers.get('authorization')?.replace('Bearer ','');if(value==='parent')return{uid:'parent',name:'Parent',email:'parent@example.com',emailVerified:true,admin:false};if(['player','friend','blocked','outsider','admin'].includes(value))return{uid:value,name:value,admin:value==='admin'};throw Object.assign(new Error('bad token'),{status:401});};const app=createApp({authenticate,repository,signingKey:key,issuer,platformOrigin:issuer,clock:()=>now,testFetchImpl:async()=>new Response('<html>',{status:200,headers:{'content-type':'text/html'}}),lookup:async()=>[{address:'93.184.216.34',family:4}],adminBootstrap:{secret:'top-secret',allowedUids:['admin'],setAdminClaim:async(uid,enabled)=>claims.push({uid,enabled})}});return{app,key,repository,claims};}
const api=(app,path,{token='player',method='POST',body,origin}={})=>app.fetch(new Request(`https://api.example${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(origin?{origin}:{})},body:body===undefined?undefined:JSON.stringify(body)}));

test('strict JWS rejects padded base64url and non-64-byte signatures',async()=>{const key=await generateES256KeyPair({kid:'strict'}),jwks=await createJwks([key]),seconds=Math.floor(now/1000),token=await signES256({iat:seconds,exp:seconds+60,jti:'jti-1234567890123',nonce:'nonce-1234567890'},key),parts=token.split('.');await assert.rejects(()=>verifyES256(`${parts[0]}=.${parts[1]}.${parts[2]}`,{jwks,now:seconds}),/base64url/);await assert.rejects(()=>verifyES256(`${parts[0]}.${parts[1]}.AA`,{jwks,now:seconds}),/64 bytes/);});

test('launch JTI is atomically consumed once and event sequence cannot replay',async()=>{const{app}=await setup(),issued=await api(app,'/v1/launch-tokens',{body:{gameId:'bowling',permissions:['profile:basic']}}),{token}=await issued.json(),first=await api(app,'/v1/launches/consume',{body:{token},origin:gameOrigin});assert.equal(first.status,201);const{channelToken}=await first.json();assert.equal((await api(app,'/v1/launches/consume',{body:{token},origin:gameOrigin})).status,409);assert.equal((await api(app,'/v1/launches/events',{body:{channelToken,sequence:1,type:'ready',payload:{protocol:2,gameId:'bowling'}},origin:gameOrigin})).status,202);assert.equal((await api(app,'/v1/launches/events',{body:{channelToken,sequence:1,type:'ready',payload:{protocol:2,gameId:'bowling'}},origin:gameOrigin})).status,409);});

test('SDK pass is created only by signed challenge consumption and claimed by its owner',async()=>{const{app,repository}=await setup(),created=await api(app,'/v1/sdk-checks',{body:{gameId:'new-game',url:'https://game.example/play'}});assert.equal(created.status,201);const challenge=await created.json();assert.equal((await api(app,`/v1/sdk-checks/${challenge.id}`,{method:'GET'})).status,200);const consumed=await api(app,'/v1/launches/consume',{body:{token:challenge.token},origin:gameOrigin});assert.equal(consumed.status,201);const claimed=await api(app,`/v1/sdk-checks/${challenge.id}/claim`,{body:{gameId:'new-game',title:'New Game',url:'https://game.example/play',ageRating:'E',notes:''}});assert.equal(claimed.status,200);assert.equal(repository.games.get('new-game').sdkPassed,true);assert.equal((await api(app,`/v1/sdk-checks/${challenge.id}/claim`,{token:'outsider',body:{gameId:'new-game',title:'Stolen',url:'https://game.example/play',ageRating:'E'}})).status,409);});

test('SDK challenge cannot hijack another owner and published claims only create pending URL',async()=>{const{app,repository}=await setup();assert.equal((await api(app,'/v1/sdk-checks',{token:'outsider',body:{gameId:'bowling',url:'https://evil.example/'}})).status,403);const created=await api(app,'/v1/sdk-checks',{body:{gameId:'bowling',url:'https://game.example/v2'}}),challenge=await created.json();await api(app,'/v1/launches/consume',{body:{token:challenge.token},origin:gameOrigin});const before=structuredClone(repository.games.get('bowling')),claimed=await api(app,`/v1/sdk-checks/${challenge.id}/claim`,{body:{gameId:'bowling',title:'Bowling 2',url:'https://game.example/v2',ageRating:'E',notes:'update'}});assert.equal(claimed.status,200);const after=repository.games.get('bowling');assert.equal(after.ownerId,before.ownerId);assert.equal(after.status,'published');assert.equal(after.url,before.url);assert.equal(after.pendingUrl,'https://game.example/v2');});

test('CORS preflight is complete for allowed origins and silent for rejected origins',async()=>{const{app}=await setup(),allowed=await app.fetch(new Request('https://api.example/v1/launch-tokens',{method:'OPTIONS',headers:{origin:issuer,'access-control-request-method':'POST','access-control-request-headers':'authorization, content-type'}}));assert.equal(allowed.status,204);assert.equal(allowed.headers.get('access-control-allow-origin'),issuer);assert.match(allowed.headers.get('access-control-allow-methods'),/POST/);assert.match(allowed.headers.get('access-control-allow-headers'),/authorization/);assert.equal(allowed.headers.get('access-control-max-age'),'600');const rejected=await app.fetch(new Request('https://api.example/v1/launch-tokens',{method:'OPTIONS',headers:{origin:'https://evil.example','access-control-request-method':'POST','access-control-request-headers':'content-type'}}));assert.equal(rejected.status,403);assert.equal(rejected.headers.has('access-control-allow-origin'),false);});

test('identity provisioning rejects impossible dates and writes age plus parent state atomically',async()=>{const{app,repository}=await setup();assert.throws(()=>deriveAgeBand('2020-02-30',new Date(now)),/invalid/);const failed=await api(app,'/v1/onboarding/age-band',{token:'outsider',body:{dateOfBirth:'2018-01-01'}});assert.equal(failed.status,400);assert.equal(repository.identities.has('outsider'),false);const ok=await api(app,'/v1/onboarding/age-band',{token:'outsider',body:{dateOfBirth:'2018-01-01',parentEmail:'parent@example.com'}});assert.equal(ok.status,201);assert.equal(repository.identities.get('outsider').ageBand,'U13');assert.equal(repository.parentConsents.get('outsider').status,'pending');});

test('reports require target access and preserved evidence carries retention metadata',async()=>{const{app,repository}=await setup();assert.equal((await api(app,'/v1/reports',{token:'outsider',body:{targetKind:'message',targetId:'secret',reason:'steal'}})).status,403);const accepted=await api(app,'/v1/reports',{body:{targetKind:'message',targetId:'secret',reason:'abuse'}});assert.equal(accepted.status,201);const evidence=[...repository.evidence.values()][0];assert.equal(evidence.legalHold,true);assert.ok(evidence.retentionUntil>now);assert.match(evidence.sha256,/^[a-f0-9]{64}$/);});

test('trusted thread routes require accepted friendship and chat for every recipient',async()=>{const{app}=await setup();assert.equal((await api(app,'/v1/threads',{body:{members:['player','outsider'],name:'bad'}})).status,403);assert.equal((await api(app,'/v1/threads',{body:{members:['player','blocked'],name:'bad'}})).status,403);const thread=await api(app,'/v1/threads',{body:{members:['player','friend'],name:'ok'}});assert.equal(thread.status,201);const{id}=await thread.json();assert.equal((await api(app,`/v1/threads/${id}/messages`,{body:{text:'hello',kind:'private'}})).status,201);});

test('missing chat policy is denied instead of treated as allowed',async()=>{const{app,repository}=await setup();repository.friendships.add('outsider:player');assert.equal(repository.chatAllowed.has('outsider'),false);assert.equal((await api(app,'/v1/threads',{body:{members:['player','outsider'],name:'unknown'}})).status,403);});

test('parent approval and moderation go through trusted routes with audit',async()=>{const{app,repository}=await setup();await api(app,'/v1/onboarding/age-band',{token:'outsider',body:{dateOfBirth:'2018-01-01',parentEmail:'parent@example.com'}});assert.equal((await api(app,'/v1/parent-consents/outsider/approve',{token:'friend',body:{}})).status,403);assert.equal((await api(app,'/v1/parent-consents/outsider/approve',{token:'parent',body:{}})).status,200);await api(app,'/v1/reports',{body:{targetKind:'message',targetId:'secret',reason:'abuse'}});const reportId=[...repository.reports.keys()][0];assert.equal((await api(app,`/v1/admin/reports/${reportId}/moderate`,{token:'admin',body:{action:'ban'}})).status,200);assert.ok(repository.audit.some(item=>item.action==='parent-consent-approved'));assert.ok(repository.audit.some(item=>item.action==='report-ban'));});

test('cleanup keeps open evidence but releases expired resolved holds and their messages',async()=>{const{app,repository}=await setup();await api(app,'/v1/reports',{body:{targetKind:'message',targetId:'secret',reason:'abuse'}});const reportId=[...repository.reports.keys()][0],evidence=[...repository.evidence.values()][0];evidence.retentionUntil=now-1;repository.reports.get(reportId).retentionUntil=now-1;let result=await repository.cleanupExpired({now});assert.equal(result.evidenceDeleted,0);assert.equal(repository.messages.has('secret'),true);await repository.moderateReport({reportId,action:'dismiss',actorId:'admin',now});result=await repository.cleanupExpired({now});assert.equal(result.evidenceDeleted,1);assert.equal(repository.messages.has('secret'),false);});

test('SSRF guard rejects private IPv4 embedded in compatible, NAT64 and 6to4 IPv6',()=>{for(const address of ['::192.168.1.1','::ffff:192.168.1.1','64:ff9b::c0a8:101','2002:c0a8:0101::1'])assert.equal(isPrivateAddress(address),true,address);});

test('event endpoint rejects unknown types, oversized payloads and missing permissions',async()=>{const{app}=await setup(),issued=await api(app,'/v1/launch-tokens',{body:{gameId:'bowling',permissions:['profile:basic']}}),{token}=await issued.json(),consumed=await api(app,'/v1/launches/consume',{body:{token},origin:gameOrigin}),{channelToken}=await consumed.json();assert.equal((await api(app,'/v1/launches/events',{body:{channelToken,sequence:1,type:'owned',payload:{}},origin:gameOrigin})).status,400);assert.equal((await api(app,'/v1/launches/events',{body:{channelToken,sequence:1,type:'presence',payload:{status:'playing',gameId:'bowling'}},origin:gameOrigin})).status,409);assert.equal((await api(app,'/v1/launches/events',{body:{channelToken,sequence:1,type:'error',payload:{code:'x',message:'x'.repeat(600)}},origin:gameOrigin})).status,400);});

test('admin bootstrap needs both allowlisted identity and constant secret, then audits claims',async()=>{const{app,claims,repository}=await setup();assert.equal((await api(app,'/v1/admin/bootstrap',{token:'admin',body:{}})).status,403);const response=await app.fetch(new Request('https://api.example/v1/admin/bootstrap',{method:'POST',headers:{authorization:'Bearer admin','x-gg-bootstrap-secret':'top-secret'}}));assert.equal(response.status,200);assert.deepEqual(claims,[{uid:'admin',enabled:true}]);assert.equal(repository.audit[0].action,'admin-bootstrap');});

test('Firestore denies direct identity, chat, report and trusted age writes and published URL mutation',()=>{const rules=fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8');for(const marker of ['match /private/identity','match /threads/{id}','match /reports/{id}','match /ageBands/{uid}'])assert.match(rules,new RegExp(marker.replace(/[{}\/]/g,'\\$&')));assert.match(rules,/allow create, update, delete: if false/);assert.match(rules,/resource\.data\.status != 'published' \|\| request\.resource\.data\.url == resource\.data\.url/);});

test('Node monitor transport pins the validated address into TLS lookup',async()=>{let captured;const requestImpl=(options,onResponse)=>{captured=options;const request=new EventEmitter();request.end=()=>options.lookup(options.hostname,{},(error,address,family)=>{assert.ifError(error);assert.equal(address,'93.184.216.34');assert.equal(family,4);const response=Readable.from([Buffer.from('ok')]);response.statusCode=200;response.headers={'content-type':'text/html'};onResponse(response);});request.destroy=error=>request.emit('error',error);return request;};const transport=createNodePinnedTransport({requestImpl});const response=await transport.fetch(new URL('https://game.example/path'),{addresses:['93.184.216.34']});assert.equal(await response.text(),'ok');assert.equal(captured.servername,'game.example');assert.equal(captured.rejectUnauthorized,true);});

test('Bowling verifies before redirect and consumes only once at the target role',async()=>{const bridge=await import(pathToFileURL('/Users/jurek/Downloads/Claude/Projects/Gzowo Bowling/v1.9/js/gg-bridge.js')),key=await generateES256KeyPair({kid:'bowl'}),jwks=await createJwks([key]),seconds=Math.floor(now/1000),payload={iss:issuer,aud:'https://bowling.example',v:2,sub:'player',game:'bowling',gameOrigin:'https://bowling.example',platformOrigin:issuer,age:'18+',permissions:['session:join'],sessionId:'s1',joinData:{room:'MILA'},nonce:'nonce-1234567890',jti:'jti-1234567890123',iat:seconds,exp:seconds+60},token=await signES256(payload,key);let consumes=0;const fetchImpl=async url=>String(url).includes('jwks')?new Response(JSON.stringify(jwks),{status:200}):(consumes+=1,new Response(JSON.stringify({channelToken:'channel',protocol:2}),{status:201}));const launch=await bridge.parseGGLaunch('','https://bowling.example',now,`#ggLaunch=${token}`,{issuer,jwksUrl:`${issuer}/jwks`,consumeUrl:`${issuer}/consume`,fetchImpl});assert.equal(launch.payload.v,2);assert.equal(consumes,0);await launch.consume();await launch.consume();assert.equal(consumes,1);const parts=token.split('.');await assert.rejects(()=>bridge.parseGGLaunch('','https://bowling.example',now,`#ggLaunch=${parts[0]}.${parts[1]}.AA`,{issuer,jwksUrl:`${issuer}/jwks`,consumeUrl:`${issuer}/consume`,fetchImpl}),/JWS/);});
